"""تحميل بيانات موسّعة: مواد فعالة + تداخلات معروفة"""

from src.database import Session, ActiveIngredient, Interaction, BrandName


# ===== قاموس الأسماء العربية =====
ARABIC_NAMES = {
    "ibuprofen": "إيبوبروفين", "aspirin": "أسبرين", "paracetamol": "باراسيتامول",
    "naproxen": "نابروكسين", "diclofenac": "ديكلوفيناك", "ketorolac": "كيتورولاك",
    "tramadol": "ترامادول", "celecoxib": "سيليكوكسيب", "indomethacin": "إندوميثاسين",
    "meloxicam": "ميلوكسيكام", "morphine": "مورفين", "codeine": "كودايين",
    "fentanyl": "فنتانيل", "warfarin": "وارفارين", "clopidogrel": "كلوبيدوجريل",
    "atorvastatin": "أتورفاستاتين", "simvastatin": "سيمفاستاتين",
    "rosuvastatin": "روسوفاستاتين", "lisinopril": "ليسينوبريل",
    "amlodipine": "أملوديبين", "bisoprolol": "بيسوبرولول", "metoprolol": "ميتوبرولول",
    "atenolol": "أتينولول", "furosemide": "فوروسيميد", "spironolactone": "سبيرونولاكتون",
    "hydrochlorothiazide": "هيدروكلوروثيازيد", "losartan": "لوسارتان",
    "valsartan": "فالسارتان", "ramipril": "راميبريل", "digoxin": "ديجوكسين",
    "amiodarone": "أميودارون", "nitroglycerin": "نيتروجليسرين", "metformin": "ميتفورمين",
    "insulin": "إنسولين", "glibenclamide": "جليبنكلاميد", "glimepiride": "جليمبريد",
    "sitagliptin": "سيتاجليبتين", "clarithromycin": "كلاريثرومايسين",
    "azithromycin": "أزيثرومايسين", "erythromycin": "إريثرومايسين",
    "ciprofloxacin": "سيبروفلوكساسين", "levofloxacin": "ليفوفلوكساسين",
    "moxifloxacin": "موكسيفلوكساسين", "ceftriaxone": "سيفترياكسون",
    "amoxicillin": "أموكسيسيلين", "metronidazole": "ميترونيدازول",
    "doxycycline": "دوكسيسايكلين", "rifampin": "ريفامبيسين",
    "ketoconazole": "كيتوكونازول", "fluconazole": "فلوكونازول",
    "itraconazole": "إيتراكونازول", "acyclovir": "أسيكلوفير", "citalopram": "سيتالوبرام",
    "sertraline": "سيرترالين", "fluoxetine": "فلووكستين", "paroxetine": "باروكستين",
    "venlafaxine": "فينلافاكسين", "quetiapine": "كويتيابين", "olanzapine": "أولانزابين",
    "risperidone": "ريسبيريدون", "lithium": "ليثيوم", "carbamazepine": "كاربامازيبين",
    "phenytoin": "فينيتوين", "valproic acid": "حمض الفالبرويك", "lamotrigine": "لاموتريجين",
    "diazepam": "ديازيبام", "alprazolam": "ألبرازولام", "omeprazole": "أوميبرازول",
    "pantoprazole": "بانتوبرازول", "esomeprazole": "إيزوميبرازول",
    "ranitidine": "رانيتيدين", "ondansetron": "أوندانسيترون",
    "metoclopramide": "ميتوكلوبراميد", "salbutamol": "سالبوتامول",
    "formoterol": "فورموتيرول", "montelukast": "مونتيلوكاست",
    "theophylline": "ثيوفيلين", "levothyroxine": "ليفوثيروكسين",
    "methimazole": "ميثيمازول", "methotrexate": "ميثوتريكسات",
    "dexamethasone": "ديكساميثازون", "prednisolone": "بريدنيزولون",
    "hydrocortisone": "هيدروكورتيزون", "aprepitant": "أبريبيتانت",
    "heparin": "هيبارين", "potassium chloride": "كلوريد البوتاسيوم",
    "promethazine": "بروميثازين", "tacrolimus": "تاكروليمس",
    "cyclosporine": "سيكلوسبورين", "sildenafil": "سيلدينافيل",
    "allopurinol": "ألوبيورينول", "colchicine": "كولشيسين", "azathioprine": "آزاثيوبرين",
    "gabapentin": "جابابنتين", "pregabalin": "بريجابالين", "escitalopram": "إسيتالوبرام",
    "duloxetine": "دولوكستين", "clonazepam": "كلونازيبام", "aripiprazole": "أريبيبرازول",
    "apixaban": "أبيكسابان", "rivaroxaban": "ريفاروكسابان", "dabigatran": "دابيجاتران",
    "dapagliflozin": "داباجليفلوزين", "empagliflozin": "إمباجليفلوزين",
    "vildagliptin": "فيلداجليبتين", "etoricoxib": "إيتوريكوكسيب",
    "tadalafil": "تادالافيل", "azithromycin": "أزيثرومايسين",
    "levetiracetam": "ليفيتيراسيتام", "linagliptin": "ليناجليبتين",
    "canagliflozin": "كاناجليفلوزين", "tiotropium": "تيوتروبيوم",
    "semaglutide": "سيماجلوتيد", "dulaglutide": "دولاجلوتيد",
    "liraglutide": "ليراجلوتيد", "tirzepatide": "تيرزيباتيد",
    "rituximab": "ريتوكسيماب", "glatiramer": "جلاتيرامر",
    "cladribine": "كلادريبين", "pembrolizumab": "بيمبروليزوماب",
    "atezolizumab": "أتيزوليزوماب", "zanubrutinib": "زانوبروتينيب",
    "ibrutinib": "إيبروتينيب", "blinatumomab": "بليناتوموماب",
    "colistin": "كوليستين", "sofosbuvir": "سوفوسبوفير",
    "velpatasvir": "فيلباتاسفير", "dolutegravir": "دولوتيجريفير",
    "tenofovir": "تينوفوفير", "emtricitabine": "إمترسيتابين",
    "lamivudine": "لاميفودين", "delamanid": "ديلامانيد",
    "clofazimine": "كلوفازيمين", "dasatinib": "داساتينيب",
    "nilotinib": "نيلوتينيب", "ravidasvir": "رافيداسفير",
    "ceftolozane": "سيفتولوزان", "tazobactam": "تازوباكتام",
    "perindopril": "بيريندوبريل", "carvedilol": "كارفيديلول",
    "doxazosin": "دوكسازوسين", "isosorbide dinitrate": "أيزوسوربيد داي نايترات",
    "betahistine": "بيتاهيستين", "alendronate": "أليندرونات",
}


# ===== قاموس الأسماء التجارية =====
BRAND_NAMES = {
    "advil": "ibuprofen", "motrin": "ibuprofen", "brufen": "ibuprofen",
    "nurofen": "ibuprofen", "voltaren": "diclofenac", "cataflam": "diclofenac",
    "aleve": "naproxen", "naprosyn": "naproxen", "toradol": "ketorolac",
    "celebrex": "celecoxib", "indocin": "indomethacin", "mobic": "meloxicam",
    "aspocid": "aspirin", "disprin": "aspirin", "panadol": "paracetamol",
    "tylenol": "paracetamol", "adol": "paracetamol", "ultracet": "tramadol",
    "tramal": "tramadol", "coumadin": "warfarin", "marevan": "warfarin",
    "plavix": "clopidogrel", "lipitor": "atorvastatin", "zocor": "simvastatin",
    "crestor": "rosuvastatin", "zestril": "lisinopril", "prinivil": "lisinopril",
    "norvasc": "amlodipine", "concor": "bisoprolol", "lopressor": "metoprolol",
    "tenormin": "atenolol", "lasix": "furosemide", "aldactone": "spironolactone",
    "esidrex": "hydrochlorothiazide", "cozaar": "losartan", "diovan": "valsartan",
    "tritace": "ramipril", "lanoxin": "digoxin", "cordarone": "amiodarone",
    "nitrostat": "nitroglycerin", "glucophage": "metformin", "lantus": "insulin",
    "humalog": "insulin", "novorapid": "insulin", "daonil": "glibenclamide",
    "amaryl": "glimepiride", "januvia": "sitagliptin", "klacid": "clarithromycin",
    "biaxin": "clarithromycin", "zithromax": "azithromycin", "zomax": "azithromycin",
    "erythrocin": "erythromycin", "cipro": "ciprofloxacin", "cifran": "ciprofloxacin",
    "levaquin": "levofloxacin", "avelox": "moxifloxacin", "rocephin": "ceftriaxone",
    "amoxil": "amoxicillin", "augmentin": "amoxicillin", "flagyl": "metronidazole",
    "vibramycin": "doxycycline", "rifadin": "rifampin", "nizoral": "ketoconazole",
    "diflucan": "fluconazole", "sporanox": "itraconazole", "zovirax": "acyclovir",
    "celexa": "citalopram", "zoloft": "sertraline", "prozac": "fluoxetine",
    "paxil": "paroxetine", "effexor": "venlafaxine", "seroquel": "quetiapine",
    "zyprexa": "olanzapine", "risperdal": "risperidone", "lithobid": "lithium",
    "tegretol": "carbamazepine", "dilantin": "phenytoin", "depakine": "valproic acid",
    "lamictal": "lamotrigine", "valium": "diazepam", "xanax": "alprazolam",
    "losec": "omeprazole", "prilosec": "omeprazole", "protonix": "pantoprazole",
    "nexium": "esomeprazole", "zantac": "ranitidine", "zofran": "ondansetron",
    "primperan": "metoclopramide", "ventolin": "salbutamol", "proventil": "salbutamol",
    "foradil": "formoterol", "singulair": "montelukast", "theo-dur": "theophylline",
    "eltroxin": "levothyroxine", "synthroid": "levothyroxine",
    "tapazole": "methimazole", "rheumatrex": "methotrexate",
    "decadron": "dexamethasone", "solu-medrol": "prednisolone",
    "cortef": "hydrocortisone", "emend": "aprepitant", "heparin sodium": "heparin",
    "slow-k": "potassium chloride", "phenergan": "promethazine",
    "prograf": "tacrolimus", "neoral": "cyclosporine", "viagra": "sildenafil",
    "zyloprim": "allopurinol", "colcrys": "colchicine", "imuran": "azathioprine",
    "neksium": "esomeprazole", "controloc": "pantoprazole", "zurcal": "pantoprazole",
    "pantoloc": "pantoprazole", "forxiga": "dapagliflozin", "xigduo": "dapagliflozin",
    "galvus": "vildagliptin", "covalmet": "vildagliptin", "atcocoxib": "etoricoxib",
    "rocoxar": "etoricoxib", "arcoxia": "etoricoxib", "neurontin": "gabapentin",
    "gabaverona": "gabapentin", "cialis": "tadalafil", "tadatrona": "tadalafil",
    "eliquis": "apixaban", "apixguard": "apixaban", "jardiance": "empagliflozin",
    "empodiab": "empagliflozin", "azibactocin": "azithromycin",
    "coversyl": "perindopril", "dilatrend": "carvedilol", "cardura": "doxazosin",
    "isordil": "isosorbide dinitrate", "betaserc": "betahistine",
    "fosamax": "alendronate", "keppra": "levetiracetam", "cipralex": "escitalopram",
    "abilify": "aripiprazole", "rivotril": "clonazepam", "cymbalta": "duloxetine",
    "lyrica": "pregabalin", "trajenta": "linagliptin", "invokana": "canagliflozin",
    "xarelto": "rivaroxaban", "pradaxa": "dabigatran", "spiriva": "tiotropium",
}


# ===== المواد الفعالة =====
INGREDIENTS = [
    # مسكنات
    {"name": "ibuprofen", "rxnorm_cui": "5640"},
    {"name": "aspirin", "rxnorm_cui": "1191"},
    {"name": "paracetamol", "rxnorm_cui": "161"},
    {"name": "naproxen", "rxnorm_cui": "7258"},
    {"name": "diclofenac", "rxnorm_cui": "3355"},
    {"name": "ketorolac", "rxnorm_cui": "35827"},
    {"name": "tramadol", "rxnorm_cui": "10689"},
    {"name": "celecoxib", "rxnorm_cui": "140587"},
    {"name": "indomethacin", "rxnorm_cui": "5781"},
    {"name": "meloxicam", "rxnorm_cui": "41493"},
    {"name": "morphine", "rxnorm_cui": "7052"},
    {"name": "codeine", "rxnorm_cui": "2670"},
    {"name": "fentanyl", "rxnorm_cui": "4337"},
    # أدوية القلب والضغط
    {"name": "warfarin", "rxnorm_cui": "11289"},
    {"name": "clopidogrel", "rxnorm_cui": "32968"},
    {"name": "atorvastatin", "rxnorm_cui": "83367"},
    {"name": "simvastatin", "rxnorm_cui": "36567"},
    {"name": "rosuvastatin", "rxnorm_cui": "301542"},
    {"name": "lisinopril", "rxnorm_cui": "29046"},
    {"name": "amlodipine", "rxnorm_cui": "17767"},
    {"name": "bisoprolol", "rxnorm_cui": "19484"},
    {"name": "metoprolol", "rxnorm_cui": "6918"},
    {"name": "atenolol", "rxnorm_cui": "1202"},
    {"name": "furosemide", "rxnorm_cui": "4603"},
    {"name": "spironolactone", "rxnorm_cui": "9997"},
    {"name": "hydrochlorothiazide", "rxnorm_cui": "5487"},
    {"name": "losartan", "rxnorm_cui": "52175"},
    {"name": "valsartan", "rxnorm_cui": "69749"},
    {"name": "ramipril", "rxnorm_cui": "35296"},
    {"name": "digoxin", "rxnorm_cui": "3407"},
    {"name": "amiodarone", "rxnorm_cui": "703"},
    {"name": "nitroglycerin", "rxnorm_cui": "7439"},
    # أدوية السكر
    {"name": "metformin", "rxnorm_cui": "6809"},
    {"name": "insulin", "rxnorm_cui": "5856"},
    {"name": "glibenclamide", "rxnorm_cui": "4815"},
    {"name": "glimepiride", "rxnorm_cui": "25789"},
    {"name": "sitagliptin", "rxnorm_cui": "593411"},
    # مضادات حيوية
    {"name": "clarithromycin", "rxnorm_cui": "21212"},
    {"name": "azithromycin", "rxnorm_cui": "18631"},
    {"name": "erythromycin", "rxnorm_cui": "4053"},
    {"name": "ciprofloxacin", "rxnorm_cui": "2551"},
    {"name": "levofloxacin", "rxnorm_cui": "82122"},
    {"name": "moxifloxacin", "rxnorm_cui": "139462"},
    {"name": "ceftriaxone", "rxnorm_cui": "2193"},
    {"name": "amoxicillin", "rxnorm_cui": "723"},
    {"name": "metronidazole", "rxnorm_cui": "6922"},
    {"name": "doxycycline", "rxnorm_cui": "3640"},
    {"name": "rifampin", "rxnorm_cui": "9384"},
    {"name": "ketoconazole", "rxnorm_cui": "6135"},
    {"name": "fluconazole", "rxnorm_cui": "4450"},
    {"name": "itraconazole", "rxnorm_cui": "28031"},
    {"name": "acyclovir", "rxnorm_cui": "281"},
    # أدوية نفسية
    {"name": "citalopram", "rxnorm_cui": "2556"},
    {"name": "sertraline", "rxnorm_cui": "36437"},
    {"name": "fluoxetine", "rxnorm_cui": "4493"},
    {"name": "paroxetine", "rxnorm_cui": "32937"},
    {"name": "venlafaxine", "rxnorm_cui": "39786"},
    {"name": "quetiapine", "rxnorm_cui": "51272"},
    {"name": "olanzapine", "rxnorm_cui": "61381"},
    {"name": "risperidone", "rxnorm_cui": "35636"},
    {"name": "lithium", "rxnorm_cui": "6448"},
    {"name": "carbamazepine", "rxnorm_cui": "2002"},
    {"name": "phenytoin", "rxnorm_cui": "8183"},
    {"name": "valproic acid", "rxnorm_cui": "11118"},
    {"name": "lamotrigine", "rxnorm_cui": "28439"},
    {"name": "diazepam", "rxnorm_cui": "3322"},
    {"name": "alprazolam", "rxnorm_cui": "596"},
    # أدوية المعدة
    {"name": "omeprazole", "rxnorm_cui": "7646"},
    {"name": "pantoprazole", "rxnorm_cui": "40790"},
    {"name": "esomeprazole", "rxnorm_cui": "283742"},
    {"name": "ranitidine", "rxnorm_cui": "9143"},
    {"name": "ondansetron", "rxnorm_cui": "26225"},
    {"name": "metoclopramide", "rxnorm_cui": "6915"},
    # أدوية الربو
    {"name": "salbutamol", "rxnorm_cui": "435"},
    {"name": "formoterol", "rxnorm_cui": "25255"},
    {"name": "montelukast", "rxnorm_cui": "88249"},
    {"name": "theophylline", "rxnorm_cui": "10460"},
    # الغدة الدرقية
    {"name": "levothyroxine", "rxnorm_cui": "10582"},
    {"name": "methimazole", "rxnorm_cui": "6835"},
    # أخرى
    {"name": "methotrexate", "rxnorm_cui": "6851"},
    {"name": "dexamethasone", "rxnorm_cui": "3264"},
    {"name": "prednisolone", "rxnorm_cui": "8638"},
    {"name": "hydrocortisone", "rxnorm_cui": "5492"},
    {"name": "aprepitant", "rxnorm_cui": "282775"},
    {"name": "heparin", "rxnorm_cui": "5224"},
    {"name": "potassium chloride", "rxnorm_cui": "8591"},
    {"name": "promethazine", "rxnorm_cui": "8745"},
    {"name": "tacrolimus", "rxnorm_cui": "42316"},
    {"name": "cyclosporine", "rxnorm_cui": "3008"},
    {"name": "sildenafil", "rxnorm_cui": "136411"},
    {"name": "allopurinol", "rxnorm_cui": "519"},
    {"name": "colchicine", "rxnorm_cui": "2683"},
    {"name": "azathioprine", "rxnorm_cui": "1256"},
    # مواد مصرية شائعة
    {"name": "dapagliflozin", "rxnorm_cui": "1488564"},
    {"name": "vildagliptin", "rxnorm_cui": "325840"},
    {"name": "etoricoxib", "rxnorm_cui": "151467"},
    {"name": "gabapentin", "rxnorm_cui": "25480"},
    {"name": "tadalafil", "rxnorm_cui": "358263"},
    {"name": "apixaban", "rxnorm_cui": "1364430"},
    {"name": "empagliflozin", "rxnorm_cui": "1545653"},
    {"name": "perindopril", "rxnorm_cui": "54552"},
    {"name": "carvedilol", "rxnorm_cui": "20352"},
    {"name": "doxazosin", "rxnorm_cui": "3523"},
    {"name": "isosorbide dinitrate", "rxnorm_cui": "5709"},
    {"name": "betahistine", "rxnorm_cui": "1515"},
    {"name": "alendronate", "rxnorm_cui": "1490"},
    {"name": "levetiracetam", "rxnorm_cui": "114477"},
    {"name": "escitalopram", "rxnorm_cui": "321988"},
    {"name": "aripiprazole", "rxnorm_cui": "352272"},
    {"name": "clonazepam", "rxnorm_cui": "2598"},
    {"name": "duloxetine", "rxnorm_cui": "72625"},
    {"name": "pregabalin", "rxnorm_cui": "187832"},
    {"name": "linagliptin", "rxnorm_cui": "1100699"},
    {"name": "canagliflozin", "rxnorm_cui": "1372882"},
    {"name": "rivaroxaban", "rxnorm_cui": "1114195"},
    {"name": "dabigatran", "rxnorm_cui": "1037045"},
    {"name": "tiotropium", "rxnorm_cui": "69120"},
    # WHO Essential Medicines
    {"name": "semaglutide", "rxnorm_cui": "1991302"},
    {"name": "dulaglutide", "rxnorm_cui": "1598394"},
    {"name": "liraglutide", "rxnorm_cui": "602888"},
    {"name": "tirzepatide", "rxnorm_cui": "2601723"},
    {"name": "rituximab", "rxnorm_cui": "121191"},
    {"name": "glatiramer", "rxnorm_cui": "1009486"},
    {"name": "cladribine", "rxnorm_cui": "2140"},
    {"name": "pembrolizumab", "rxnorm_cui": "1547545"},
    {"name": "atezolizumab", "rxnorm_cui": "1657455"},
    {"name": "zanubrutinib", "rxnorm_cui": "2288376"},
    {"name": "ibrutinib", "rxnorm_cui": "1442981"},
    {"name": "blinatumomab", "rxnorm_cui": "1599812"},
    {"name": "colistin", "rxnorm_cui": "2507"},
    {"name": "sofosbuvir", "rxnorm_cui": "1102129"},
    {"name": "velpatasvir", "rxnorm_cui": "1747692"},
    {"name": "dolutegravir", "rxnorm_cui": "1116186"},
    {"name": "tenofovir", "rxnorm_cui": "1942896"},
    {"name": "emtricitabine", "rxnorm_cui": "211338"},
    {"name": "lamivudine", "rxnorm_cui": "6825"},
    {"name": "delamanid", "rxnorm_cui": "1593673"},
    {"name": "clofazimine", "rxnorm_cui": "2579"},
    {"name": "dasatinib", "rxnorm_cui": "358312"},
    {"name": "nilotinib", "rxnorm_cui": "705793"},
    {"name": "ravidasvir", "rxnorm_cui": "2049414"},
    {"name": "ceftolozane", "rxnorm_cui": "1249352"},
    {"name": "tazobactam", "rxnorm_cui": "11314"},
]


# ===== التداخلات =====
INTERACTIONS = [
    {"a": "warfarin", "b": "aspirin", "severity": "major",
     "description": "زيادة خطر النزيف.", "management": "تجنب الجمع إلا لو ضروري. راقب INR."},
    {"a": "warfarin", "b": "ibuprofen", "severity": "major",
     "description": "الإيبوبروفين يزيد تأثير الوارفارين.", "management": "استخدم باراسيتامول بديلاً. راقب INR."},
    {"a": "warfarin", "b": "naproxen", "severity": "major",
     "description": "زيادة خطر النزيف.", "management": "تجنب الجمع."},
    {"a": "warfarin", "b": "diclofenac", "severity": "major",
     "description": "زيادة خطر النزيف.", "management": "تجنب الجمع."},
    {"a": "warfarin", "b": "celecoxib", "severity": "major",
     "description": "زيادة خطر النزيف.", "management": "تجنب الجمع أو راقب INR."},
    {"a": "warfarin", "b": "meloxicam", "severity": "major",
     "description": "زيادة خطر النزيف.", "management": "تجنب الجمع."},
    {"a": "warfarin", "b": "indomethacin", "severity": "major",
     "description": "زيادة خطر النزيف.", "management": "تجنب الجمع."},
    {"a": "warfarin", "b": "clarithromycin", "severity": "major",
     "description": "يزيد تأثير الوارفارين.", "management": "راقب INR."},
    {"a": "warfarin", "b": "azithromycin", "severity": "major",
     "description": "يزيد تأثير الوارفارين.", "management": "راقب INR."},
    {"a": "warfarin", "b": "erythromycin", "severity": "major",
     "description": "يزيد تأثير الوارفارين.", "management": "راقب INR."},
    {"a": "warfarin", "b": "ciprofloxacin", "severity": "major",
     "description": "يزيد تأثير الوارفارين.", "management": "راقب INR."},
    {"a": "warfarin", "b": "levofloxacin", "severity": "major",
     "description": "يزيد تأثير الوارفارين.", "management": "راقب INR."},
    {"a": "warfarin", "b": "metronidazole", "severity": "major",
     "description": "يزيد تأثير الوارفارين.", "management": "راقب INR."},
    {"a": "warfarin", "b": "fluconazole", "severity": "major",
     "description": "يزيد تأثير الوارفارين.", "management": "راقب INR."},
    {"a": "warfarin", "b": "itraconazole", "severity": "major",
     "description": "يزيد تأثير الوارفارين.", "management": "راقب INR."},
    {"a": "warfarin", "b": "ketoconazole", "severity": "major",
     "description": "يزيد تأثير الوارفارين.", "management": "راقب INR."},
    {"a": "warfarin", "b": "phenytoin", "severity": "major",
     "description": "تفاعل معقد.", "management": "راقب INR ومستويات الفينيتوين."},
    {"a": "warfarin", "b": "carbamazepine", "severity": "major",
     "description": "يقلل تأثير الوارفارين.", "management": "راقب INR."},
    {"a": "warfarin", "b": "rifampin", "severity": "major",
     "description": "يقلل تأثير الوارفارين.", "management": "راقب INR."},
    {"a": "warfarin", "b": "amiodarone", "severity": "major",
     "description": "يزيد تأثير الوارفارين.", "management": "قلل الجرعة وراقب INR."},
    {"a": "warfarin", "b": "allopurinol", "severity": "major",
     "description": "يزيد تأثير الوارفارين.", "management": "راقب INR."},
    {"a": "ibuprofen", "b": "methotrexate", "severity": "major",
     "description": "يزيد سمية الميثوتريكسات.", "management": "تجنب الجمع."},
    {"a": "ibuprofen", "b": "lithium", "severity": "major",
     "description": "يزيد مستويات الليثيوم.", "management": "راقب الليثيوم."},
    {"a": "naproxen", "b": "lithium", "severity": "major",
     "description": "يزيد مستويات الليثيوم.", "management": "راقب الليثيوم."},
    {"a": "diclofenac", "b": "lithium", "severity": "major",
     "description": "يزيد مستويات الليثيوم.", "management": "راقب الليثيوم."},
    {"a": "atorvastatin", "b": "clarithromycin", "severity": "major",
     "description": "يزيد مستويات الأتورفاستاتين.", "management": "أوقف الأتورفاستاتين مؤقتاً."},
    {"a": "atorvastatin", "b": "itraconazole", "severity": "major",
     "description": "يزيد مستويات الأتورفاستاتين.", "management": "قلل الجرعة."},
    {"a": "atorvastatin", "b": "ketoconazole", "severity": "major",
     "description": "يزيد مستويات الأتورفاستاتين.", "management": "تجنب الجمع."},
    {"a": "simvastatin", "b": "clarithromycin", "severity": "major",
     "description": "يزيد مستويات السيمفاستاتين.", "management": "ممنوع الجمع."},
    {"a": "simvastatin", "b": "itraconazole", "severity": "major",
     "description": "يزيد مستويات السيمفاستاتين.", "management": "ممنوع الجمع."},
    {"a": "simvastatin", "b": "ketoconazole", "severity": "major",
     "description": "يزيد مستويات السيمفاستاتين.", "management": "ممنوع الجمع."},
    {"a": "simvastatin", "b": "erythromycin", "severity": "major",
     "description": "يزيد مستويات السيمفاستاتين.", "management": "تجنب الجمع."},
    {"a": "simvastatin", "b": "amiodarone", "severity": "major",
     "description": "يزيد مستويات السيمفاستاتين.", "management": "لا تتجاوز 20 مجم."},
    {"a": "digoxin", "b": "clarithromycin", "severity": "major",
     "description": "يزيد مستويات الديجوكسين.", "management": "راقب الديجوكسين."},
    {"a": "digoxin", "b": "amiodarone", "severity": "major",
     "description": "يزيد مستويات الديجوكسين.", "management": "قلل الجرعة."},
    {"a": "citalopram", "b": "tramadol", "severity": "major",
     "description": "خطر متلازمة السيروتونين.", "management": "تجنب الجمع."},
    {"a": "sertraline", "b": "tramadol", "severity": "major",
     "description": "خطر متلازمة السيروتونين.", "management": "تجنب الجمع."},
    {"a": "fluoxetine", "b": "tramadol", "severity": "major",
     "description": "خطر متلازمة السيروتونين.", "management": "تجنب الجمع."},
    {"a": "paroxetine", "b": "tramadol", "severity": "major",
     "description": "خطر متلازمة السيروتونين.", "management": "تجنب الجمع."},
    {"a": "venlafaxine", "b": "tramadol", "severity": "major",
     "description": "خطر متلازمة السيروتونين.", "management": "تجنب الجمع."},
    {"a": "clopidogrel", "b": "omeprazole", "severity": "major",
     "description": "يقلل تأثير الكلوبيدوجريل.", "management": "استخدم بانتوبرازول."},
    {"a": "clopidogrel", "b": "esomeprazole", "severity": "major",
     "description": "يقلل تأثير الكلوبيدوجريل.", "management": "استخدم بانتوبرازول."},
    {"a": "theophylline", "b": "ciprofloxacin", "severity": "major",
     "description": "يزيد مستويات الثيوفيلين.", "management": "راقب الثيوفيلين."},
    {"a": "theophylline", "b": "erythromycin", "severity": "major",
     "description": "يزيد مستويات الثيوفيلين.", "management": "راقب الثيوفيلين."},
    {"a": "theophylline", "b": "clarithromycin", "severity": "major",
     "description": "يزيد مستويات الثيوفيلين.", "management": "راقب الثيوفيلين."},
    {"a": "methotrexate", "b": "aspirin", "severity": "major",
     "description": "يزيد سمية الميثوتريكسات.", "management": "تجنب الجمع."},
    {"a": "methotrexate", "b": "ibuprofen", "severity": "major",
     "description": "يزيد سمية الميثوتريكسات.", "management": "تجنب الجمع."},
    {"a": "methotrexate", "b": "naproxen", "severity": "major",
     "description": "يزيد سمية الميثوتريكسات.", "management": "تجنب الجمع."},
    {"a": "tacrolimus", "b": "clarithromycin", "severity": "major",
     "description": "يزيد مستويات التاكروليمس.", "management": "راقب المستويات."},
    {"a": "tacrolimus", "b": "ketoconazole", "severity": "major",
     "description": "يزيد مستويات التاكروليمس.", "management": "تجنب الجمع."},
    {"a": "tacrolimus", "b": "itraconazole", "severity": "major",
     "description": "يزيد مستويات التاكروليمس.", "management": "راقب المستويات."},
    {"a": "cyclosporine", "b": "clarithromycin", "severity": "major",
     "description": "يزيد مستويات السيكلوسبورين.", "management": "راقب المستويات."},
    {"a": "cyclosporine", "b": "ketoconazole", "severity": "major",
     "description": "يزيد مستويات السيكلوسبورين.", "management": "راقب المستويات."},
    {"a": "cyclosporine", "b": "itraconazole", "severity": "major",
     "description": "يزيد مستويات السيكلوسبورين.", "management": "راقب المستويات."},
    {"a": "azathioprine", "b": "allopurinol", "severity": "major",
     "description": "يزيد سمية الآزاثيوبرين.", "management": "قلل الجرعة."},
    {"a": "lithium", "b": "hydrochlorothiazide", "severity": "major",
     "description": "يزيد مستويات الليثيوم.", "management": "راقب الليثيوم."},
    {"a": "lithium", "b": "furosemide", "severity": "major",
     "description": "يزيد مستويات الليثيوم.", "management": "راقب الليثيوم."},
    {"a": "lithium", "b": "lisinopril", "severity": "major",
     "description": "يزيد مستويات الليثيوم.", "management": "راقب الليثيوم."},
    {"a": "lithium", "b": "losartan", "severity": "major",
     "description": "يزيد مستويات الليثيوم.", "management": "راقب الليثيوم."},
    {"a": "amiodarone", "b": "levothyroxine", "severity": "major",
     "description": "يؤثر على الغدة الدرقية.", "management": "راقب وظائف الغدة."},
    {"a": "methimazole", "b": "warfarin", "severity": "major",
     "description": "يقلل تأثير الوارفارين.", "management": "راقب INR."},
    {"a": "colchicine", "b": "clarithromycin", "severity": "major",
     "description": "يزيد سمية الكولشيسين.", "management": "تجنب الجمع."},
    {"a": "colchicine", "b": "ketoconazole", "severity": "major",
     "description": "يزيد سمية الكولشيسين.", "management": "تجنب الجمع."},
    {"a": "colchicine", "b": "cyclosporine", "severity": "major",
     "description": "يزيد سمية الكولشيسين.", "management": "تجنب الجمع."},
    {"a": "sildenafil", "b": "nitroglycerin", "severity": "major",
     "description": "انخفاض خطير في ضغط الدم.", "management": "ممنوع الجمع."},
    {"a": "tadalafil", "b": "nitroglycerin", "severity": "major",
     "description": "انخفاض خطير في ضغط الدم.", "management": "ممنوع الجمع."},
    # تداخلات مضادات التجلط
    {"a": "apixaban", "b": "aspirin", "severity": "major",
     "description": "زيادة خطر النزيف.", "management": "تجنب الجمع."},
    {"a": "apixaban", "b": "ibuprofen", "severity": "major",
     "description": "زيادة خطر النزيف.", "management": "تجنب الجمع."},
    {"a": "apixaban", "b": "naproxen", "severity": "major",
     "description": "زيادة خطر النزيف.", "management": "تجنب الجمع."},
    {"a": "apixaban", "b": "diclofenac", "severity": "major",
     "description": "زيادة خطر النزيف.", "management": "تجنب الجمع."},
    {"a": "apixaban", "b": "warfarin", "severity": "major",
     "description": "ممنوع الجمع.", "management": "ممنوع الجمع."},
    {"a": "apixaban", "b": "clopidogrel", "severity": "major",
     "description": "زيادة خطر النزيف.", "management": "راقب النزيف."},
    {"a": "apixaban", "b": "heparin", "severity": "major",
     "description": "زيادة خطر النزيف.", "management": "راقب النزيف."},
    {"a": "rivaroxaban", "b": "aspirin", "severity": "major",
     "description": "زيادة خطر النزيف.", "management": "تجنب الجمع."},
    {"a": "rivaroxaban", "b": "ibuprofen", "severity": "major",
     "description": "زيادة خطر النزيف.", "management": "تجنب الجمع."},
    {"a": "rivaroxaban", "b": "warfarin", "severity": "major",
     "description": "ممنوع الجمع.", "management": "ممنوع الجمع."},
    {"a": "rivaroxaban", "b": "clopidogrel", "severity": "major",
     "description": "زيادة خطر النزيف.", "management": "راقب النزيف."},
    {"a": "dabigatran", "b": "aspirin", "severity": "major",
     "description": "زيادة خطر النزيف.", "management": "تجنب الجمع."},
    {"a": "dabigatran", "b": "ibuprofen", "severity": "major",
     "description": "زيادة خطر النزيف.", "management": "تجنب الجمع."},
    {"a": "dabigatran", "b": "warfarin", "severity": "major",
     "description": "ممنوع الجمع.", "management": "ممنوع الجمع."},
    {"a": "dabigatran", "b": "clopidogrel", "severity": "major",
     "description": "زيادة خطر النزيف.", "management": "راقب النزيف."},
    # تداخلات مضادات الاكتئاب
    {"a": "escitalopram", "b": "tramadol", "severity": "major",
     "description": "خطر متلازمة السيروتونين.", "management": "تجنب الجمع."},
    {"a": "duloxetine", "b": "tramadol", "severity": "major",
     "description": "خطر متلازمة السيروتونين.", "management": "تجنب الجمع."},
    {"a": "escitalopram", "b": "warfarin", "severity": "major",
     "description": "زيادة خطر النزيف.", "management": "راقب INR."},
    {"a": "duloxetine", "b": "warfarin", "severity": "major",
     "description": "زيادة خطر النزيف.", "management": "راقب INR."},
    # تداخلات مضادات الصرع
    {"a": "gabapentin", "b": "morphine", "severity": "moderate",
     "description": "زيادة التهدئة.", "management": "راقب التنفس."},
    {"a": "gabapentin", "b": "tramadol", "severity": "moderate",
     "description": "زيادة التهدئة.", "management": "راقب المريض."},
    {"a": "pregabalin", "b": "morphine", "severity": "moderate",
     "description": "زيادة التهدئة.", "management": "راقب التنفس."},
    {"a": "pregabalin", "b": "tramadol", "severity": "moderate",
     "description": "زيادة التهدئة.", "management": "راقب المريض."},
    {"a": "levetiracetam", "b": "carbamazepine", "severity": "moderate",
     "description": "مراقبة المستويات.", "management": "راقب مستويات الدواء."},
    # تداخلات البنزوديازيبينات
    {"a": "clonazepam", "b": "morphine", "severity": "moderate",
     "description": "اكتئاب التنفس.", "management": "راقب التنفس."},
    {"a": "clonazepam", "b": "tramadol", "severity": "moderate",
     "description": "زيادة التهدئة.", "management": "راقب المريض."},
    {"a": "diazepam", "b": "morphine", "severity": "moderate",
     "description": "اكتئاب التنفس.", "management": "راقب التنفس."},
    # تداخلات إيتوريكوكسيب
    {"a": "etoricoxib", "b": "warfarin", "severity": "major",
     "description": "زيادة خطر النزيف.", "management": "تجنب الجمع."},
    {"a": "etoricoxib", "b": "aspirin", "severity": "moderate",
     "description": "زيادة خطر النزيف.", "management": "تجنب الجمع."},
    {"a": "etoricoxib", "b": "ibuprofen", "severity": "moderate",
     "description": "تجنب الجمع.", "management": "تجنب الجمع."},
    {"a": "etoricoxib", "b": "naproxen", "severity": "moderate",
     "description": "تجنب الجمع.", "management": "تجنب الجمع."},
    {"a": "etoricoxib", "b": "lisinopril", "severity": "moderate",
     "description": "يقلل تأثير الليسينوبريل.", "management": "راقب الضغط."},
    {"a": "etoricoxib", "b": "furosemide", "severity": "moderate",
     "description": "يقلل تأثير المدرات.", "management": "راقب المريض."},
    {"a": "etoricoxib", "b": "losartan", "severity": "moderate",
     "description": "يقلل تأثير اللوسارتان.", "management": "راقب الضغط."},
    # تداخلات أزيثرومايسين
    {"a": "azithromycin", "b": "warfarin", "severity": "major",
     "description": "يزيد تأثير الوارفارين.", "management": "راقب INR."},
    {"a": "azithromycin", "b": "digoxin", "severity": "moderate",
     "description": "يزيد مستويات الديجوكسين.", "management": "راقب الديجوكسين."},
    {"a": "azithromycin", "b": "amiodarone", "severity": "major",
     "description": "خطر اضطراب نظم القلب.", "management": "تجنب الجمع."},
    # تداخلات أدوية السكري
    {"a": "dapagliflozin", "b": "furosemide", "severity": "moderate",
     "description": "خطر الجفاف.", "management": "راقب السوائل."},
    {"a": "dapagliflozin", "b": "insulin", "severity": "moderate",
     "description": "خطر نقص السكر.", "management": "راقب السكر."},
    {"a": "empagliflozin", "b": "furosemide", "severity": "moderate",
     "description": "خطر الجفاف.", "management": "راقب السوائل."},
    {"a": "empagliflozin", "b": "insulin", "severity": "moderate",
     "description": "خطر نقص السكر.", "management": "راقب السكر."},
    {"a": "vildagliptin", "b": "insulin", "severity": "moderate",
     "description": "خطر نقص السكر.", "management": "راقب السكر."},
    {"a": "vildagliptin", "b": "glibenclamide", "severity": "moderate",
     "description": "خطر نقص السكر.", "management": "راقب السكر."},
    # تداخلات مضادات الذهان
    {"a": "aripiprazole", "b": "diazepam", "severity": "moderate",
     "description": "زيادة التهدئة.", "management": "راقب المريض."},
    {"a": "aripiprazole", "b": "carbamazepine", "severity": "moderate",
     "description": "يقلل مستويات الأريبيبرازول.", "management": "راقب الفعالية."},
    # تداخلات تادالافيل
    {"a": "tadalafil", "b": "amlodipine", "severity": "moderate",
     "description": "انخفاض ضغط الدم.", "management": "راقب الضغط."},
    # تداخلات إيزوميبرازول
    {"a": "esomeprazole", "b": "clopidogrel", "severity": "major",
     "description": "يقلل تأثير الكلوبيدوجريل.", "management": "استخدم بانتوبرازول."},
    # تداخلات متوسطة إضافية
    {"a": "aspirin", "b": "ibuprofen", "severity": "moderate",
     "description": "يقلل تأثير الأسبرين.", "management": "خد الأسبرين قبل الإيبوبروفين بساعتين."},
    {"a": "aspirin", "b": "clopidogrel", "severity": "moderate",
     "description": "زيادة خطر النزيف.", "management": "راقب النزيف."},
    {"a": "aspirin", "b": "heparin", "severity": "moderate",
     "description": "زيادة خطر النزيف.", "management": "راقب النزيف."},
    {"a": "clopidogrel", "b": "heparin", "severity": "moderate",
     "description": "زيادة خطر النزيف.", "management": "راقب النزيف."},
    {"a": "ibuprofen", "b": "naproxen", "severity": "moderate",
     "description": "زيادة الآثار الجانبية.", "management": "تجنب الجمع."},
    {"a": "ibuprofen", "b": "diclofenac", "severity": "moderate",
     "description": "زيادة الآثار الجانبية.", "management": "تجنب الجمع."},
    {"a": "ibuprofen", "b": "celecoxib", "severity": "moderate",
     "description": "زيادة الآثار الجانبية.", "management": "تجنب الجمع."},
    {"a": "ibuprofen", "b": "lisinopril", "severity": "moderate",
     "description": "يقلل تأثير الليسينوبريل.", "management": "راقب الضغط والكلى."},
    {"a": "ibuprofen", "b": "losartan", "severity": "moderate",
     "description": "يقلل تأثير اللوسارتان.", "management": "راقب الضغط والكلى."},
    {"a": "ibuprofen", "b": "furosemide", "severity": "moderate",
     "description": "يقلل تأثير المدرات.", "management": "راقب المريض."},
    {"a": "ibuprofen", "b": "spironolactone", "severity": "moderate",
     "description": "ارتفاع البوتاسيوم.", "management": "راقب البوتاسيوم."},
    {"a": "naproxen", "b": "lisinopril", "severity": "moderate",
     "description": "يقلل تأثير الليسينوبريل.", "management": "راقب الضغط."},
    {"a": "diclofenac", "b": "lisinopril", "severity": "moderate",
     "description": "يقلل تأثير الليسينوبريل.", "management": "راقب الضغط."},
    {"a": "celecoxib", "b": "lisinopril", "severity": "moderate",
     "description": "يقلل تأثير الليسينوبريل.", "management": "راقب الضغط."},
    {"a": "simvastatin", "b": "amlodipine", "severity": "moderate",
     "description": "يزيد مستويات السيمفاستاتين.", "management": "لا تتجاوز 20 مجم."},
    {"a": "digoxin", "b": "furosemide", "severity": "moderate",
     "description": "يزيد سمية الديجوكسين.", "management": "راقب البوتاسيوم."},
    {"a": "digoxin", "b": "spironolactone", "severity": "moderate",
     "description": "يزيد مستويات الديجوكسين.", "management": "راقب الديجوكسين."},
    {"a": "digoxin", "b": "hydrochlorothiazide", "severity": "moderate",
     "description": "يزيد سمية الديجوكسين.", "management": "راقب البوتاسيوم."},
    {"a": "citalopram", "b": "aspirin", "severity": "moderate",
     "description": "زيادة النزيف المعوي.", "management": "راقب النزيف."},
    {"a": "sertraline", "b": "aspirin", "severity": "moderate",
     "description": "زيادة النزيف المعوي.", "management": "راقب النزيف."},
    {"a": "fluoxetine", "b": "aspirin", "severity": "moderate",
     "description": "زيادة النزيف المعوي.", "management": "راقب النزيف."},
    {"a": "paroxetine", "b": "aspirin", "severity": "moderate",
     "description": "زيادة النزيف المعوي.", "management": "راقب النزيف."},
    {"a": "venlafaxine", "b": "aspirin", "severity": "moderate",
     "description": "زيادة النزيف المعوي.", "management": "راقب النزيف."},
    {"a": "citalopram", "b": "ibuprofen", "severity": "moderate",
     "description": "زيادة النزيف المعوي.", "management": "راقب النزيف."},
    {"a": "sertraline", "b": "ibuprofen", "severity": "moderate",
     "description": "زيادة النزيف المعوي.", "management": "راقب النزيف."},
    {"a": "fluoxetine", "b": "ibuprofen", "severity": "moderate",
     "description": "زيادة النزيف المعوي.", "management": "راقب النزيف."},
    {"a": "paroxetine", "b": "ibuprofen", "severity": "moderate",
     "description": "زيادة النزيف المعوي.", "management": "راقب النزيف."},
    {"a": "escitalopram", "b": "aspirin", "severity": "moderate",
     "description": "زيادة النزيف المعوي.", "management": "راقب النزيف."},
    {"a": "escitalopram", "b": "ibuprofen", "severity": "moderate",
     "description": "زيادة النزيف المعوي.", "management": "راقب النزيف."},
    {"a": "duloxetine", "b": "aspirin", "severity": "moderate",
     "description": "زيادة النزيف المعوي.", "management": "راقب النزيف."},
    {"a": "duloxetine", "b": "ibuprofen", "severity": "moderate",
     "description": "زيادة النزيف المعوي.", "management": "راقب النزيف."},
    {"a": "omeprazole", "b": "clopidogrel", "severity": "moderate",
     "description": "يقلل تأثير الكلوبيدوجريل.", "management": "استخدم بانتوبرازول."},
    {"a": "paracetamol", "b": "warfarin", "severity": "moderate",
     "description": "يزيد تأثير الوارفارين.", "management": "راقب INR."},
    {"a": "amlodipine", "b": "furosemide", "severity": "moderate",
     "description": "انخفاض ضغط الدم.", "management": "راقب الضغط."},
    {"a": "ceftriaxone", "b": "furosemide", "severity": "moderate",
     "description": "سمية الكلى.", "management": "راقب وظائف الكلى."},
    {"a": "furosemide", "b": "formoterol", "severity": "moderate",
     "description": "انخفاض البوتاسيوم.", "management": "راقب البوتاسيوم."},
    {"a": "furosemide", "b": "hydrocortisone", "severity": "moderate",
     "description": "انخفاض البوتاسيوم.", "management": "راقب البوتاسيوم."},
    {"a": "furosemide", "b": "prednisolone", "severity": "moderate",
     "description": "انخفاض البوتاسيوم.", "management": "راقب البوتاسيوم."},
    {"a": "furosemide", "b": "dexamethasone", "severity": "moderate",
     "description": "انخفاض البوتاسيوم.", "management": "راقب البوتاسيوم."},
    {"a": "furosemide", "b": "salbutamol", "severity": "moderate",
     "description": "انخفاض البوتاسيوم.", "management": "راقب البوتاسيوم."},
    {"a": "losartan", "b": "furosemide", "severity": "moderate",
     "description": "انخفاض الضغط أو سمية الكلى.", "management": "راقب الضغط والكلى."},
    {"a": "losartan", "b": "spironolactone", "severity": "moderate",
     "description": "ارتفاع البوتاسيوم.", "management": "راقب البوتاسيوم."},
    {"a": "lisinopril", "b": "spironolactone", "severity": "moderate",
     "description": "ارتفاع البوتاسيوم.", "management": "راقب البوتاسيوم."},
    {"a": "lisinopril", "b": "potassium chloride", "severity": "moderate",
     "description": "ارتفاع البوتاسيوم.", "management": "راقب البوتاسيوم."},
    {"a": "levofloxacin", "b": "aspirin", "severity": "moderate",
     "description": "يقلل تركيز الكينولونات.", "management": "راقب الفعالية."},
    {"a": "furosemide", "b": "aspirin", "severity": "moderate",
     "description": "يزيد الساليسيلات.", "management": "راقب السمية."},
    {"a": "aprepitant", "b": "dexamethasone", "severity": "moderate",
     "description": "يزيد تركيز الديكساميثازون.", "management": "قلل الجرعة."},
    {"a": "aprepitant", "b": "prednisolone", "severity": "moderate",
     "description": "يزيد تركيز الكورتيكوستيرويدات.", "management": "قلل الجرعة."},
    {"a": "valproic acid", "b": "aspirin", "severity": "moderate",
     "description": "يزيد مستويات الفالبرويك.", "management": "راقب المستويات."},
    {"a": "quetiapine", "b": "ketorolac", "severity": "moderate",
     "description": "زيادة الآثار الجانبية.", "management": "راقب المريض."},
    {"a": "quetiapine", "b": "hydrochlorothiazide", "severity": "moderate",
     "description": "انخفاض الضغط.", "management": "راقب الضغط."},
    {"a": "olanzapine", "b": "diazepam", "severity": "moderate",
     "description": "زيادة التهدئة.", "management": "راقب المريض."},
    {"a": "risperidone", "b": "furosemide", "severity": "moderate",
     "description": "انخفاض الضغط.", "management": "راقب الضغط."},
    {"a": "tramadol", "b": "diazepam", "severity": "moderate",
     "description": "زيادة التهدئة.", "management": "راقب التنفس."},
    {"a": "codeine", "b": "diazepam", "severity": "moderate",
     "description": "زيادة التهدئة.", "management": "راقب المريض."},
    {"a": "alprazolam", "b": "morphine", "severity": "moderate",
     "description": "اكتئاب التنفس.", "management": "راقب التنفس."},
    {"a": "levothyroxine", "b": "omeprazole", "severity": "moderate",
     "description": "يقلل امتصاص الليفوثيروكسين.", "management": "خد الليفوثيروكسين على معدة فاضية."},
    {"a": "levothyroxine", "b": "pantoprazole", "severity": "moderate",
     "description": "يقلل امتصاص الليفوثيروكسين.", "management": "خد الليفوثيروكسين على معدة فاضية."},
    # تداخلات بسيطة
    {"a": "metformin", "b": "furosemide", "severity": "minor",
     "description": "قد تؤثر على السكر.", "management": "راقب السكر."},
    {"a": "clopidogrel", "b": "atorvastatin", "severity": "minor",
     "description": "يقلل تأثير الكلوبيدوجريل.", "management": "راقب الفعالية."},
    {"a": "metformin", "b": "pantoprazole", "severity": "minor",
     "description": "يزيد تركيز الميتفورمين.", "management": "راقب السكر."},
]


def load_data():
    """تعبئة قاعدة البيانات بالبيانات المبدئية"""
    session = Session()

    try:
        # ===== إضافة المواد الفعالة =====
        print("📥 جاري إضافة المواد الفعالة...")
        ingredient_map = {}
        added_ingredients = 0

        for item in INGREDIENTS:
            existing = session.query(ActiveIngredient).filter_by(name=item["name"]).first()
            name_ar = ARABIC_NAMES.get(item["name"])

            if not existing:
                ing = ActiveIngredient(
                    name=item["name"],
                    name_ar=name_ar,
                    rxnorm_cui=item["rxnorm_cui"]
                )
                session.add(ing)
                session.flush()
                ingredient_map[item["name"]] = ing.id
                added_ingredients += 1
            else:
                if name_ar and not existing.name_ar:
                    existing.name_ar = name_ar
                ingredient_map[item["name"]] = existing.id

        session.commit()
        print(f"✅ تمت إضافة {added_ingredients} مادة فعالة جديدة (الإجمالي: {len(ingredient_map)})")

        # ===== إضافة الأسماء التجارية =====
        print("\n📥 جاري إضافة الأسماء التجارية...")
        added_brands = 0
        for brand, ing_name in BRAND_NAMES.items():
            ing_id = ingredient_map.get(ing_name)
            if not ing_id:
                continue
            existing = session.query(BrandName).filter_by(brand_name=brand).first()
            if not existing:
                session.add(BrandName(brand_name=brand, ingredient_id=ing_id))
                added_brands += 1
        session.commit()
        print(f"✅ تمت إضافة {added_brands} اسم تجاري جديد")

        # ===== إضافة التداخلات =====
        print("\n📥 جاري إضافة التداخلات...")
        added = 0
        skipped = 0

        for inter in INTERACTIONS:
            a_id = ingredient_map.get(inter["a"])
            b_id = ingredient_map.get(inter["b"])

            if not a_id or not b_id:
                print(f"⚠️ مادة غير موجودة: {inter['a']} أو {inter['b']}")
                continue

            if a_id > b_id:
                a_id, b_id = b_id, a_id

            existing = session.query(Interaction).filter_by(
                ingredient_a_id=a_id,
                ingredient_b_id=b_id
            ).first()

            if not existing:
                interaction = Interaction(
                    ingredient_a_id=a_id,
                    ingredient_b_id=b_id,
                    severity=inter["severity"],
                    description=inter["description"],
                    management=inter["management"],
                    source="manual"
                )
                session.add(interaction)
                added += 1
            else:
                skipped += 1

        session.commit()
        print(f"✅ تمت إضافة {added} تداخل دوائي جديد (تم تخطي {skipped} موجود)")

    except Exception as e:
        session.rollback()
        print(f"❌ خطأ: {e}")
    finally:
        session.close()


if __name__ == "__main__":
    load_data()