"""تحميل بيانات موسّعة: مواد فعالة + تداخلات معروفة"""

from src.database import Session, ActiveIngredient, Interaction, BrandName


# ===== قاموس الأسماء العربية =====
ARABIC_NAMES = {
    "ibuprofen": "إيبوبروفين",
    "aspirin": "أسبرين",
    "paracetamol": "باراسيتامول",
    "naproxen": "نابروكسين",
    "diclofenac": "ديكلوفيناك",
    "ketorolac": "كيتورولاك",
    "tramadol": "ترامادول",
    "celecoxib": "سيليكوكسيب",
    "indomethacin": "إندوميثاسين",
    "meloxicam": "ميلوكسيكام",
    "morphine": "مورفين",
    "codeine": "كودايين",
    "fentanyl": "فنتانيل",
    "warfarin": "وارفارين",
    "clopidogrel": "كلوبيدوجريل",
    "atorvastatin": "أتورفاستاتين",
    "simvastatin": "سيمفاستاتين",
    "rosuvastatin": "روسوفاستاتين",
    "lisinopril": "ليسينوبريل",
    "amlodipine": "أملوديبين",
    "bisoprolol": "بيسوبرولول",
    "metoprolol": "ميتوبرولول",
    "atenolol": "أتينولول",
    "furosemide": "فوروسيميد",
    "spironolactone": "سبيرونولاكتون",
    "hydrochlorothiazide": "هيدروكلوروثيازيد",
    "losartan": "لوسارتان",
    "valsartan": "فالسارتان",
    "ramipril": "راميبريل",
    "digoxin": "ديجوكسين",
    "amiodarone": "أميودارون",
    "nitroglycerin": "نيتروجليسرين",
    "metformin": "ميتفورمين",
    "insulin": "إنسولين",
    "glibenclamide": "جليبنكلاميد",
    "glimepiride": "جليمبريد",
    "sitagliptin": "سيتاجليبتين",
    "clarithromycin": "كلاريثرومايسين",
    "azithromycin": "أزيثرومايسين",
    "erythromycin": "إريثرومايسين",
    "ciprofloxacin": "سيبروفلوكساسين",
    "levofloxacin": "ليفوفلوكساسين",
    "moxifloxacin": "موكسيفلوكساسين",
    "ceftriaxone": "سيفترياكسون",
    "amoxicillin": "أموكسيسيلين",
    "metronidazole": "ميترونيدازول",
    "doxycycline": "دوكسيسايكلين",
    "rifampin": "ريفامبيسين",
    "ketoconazole": "كيتوكونازول",
    "fluconazole": "فلوكونازول",
    "itraconazole": "إيتراكونازول",
    "acyclovir": "أسيكلوفير",
    "citalopram": "سيتالوبرام",
    "sertraline": "سيرترالين",
    "fluoxetine": "فلووكستين",
    "paroxetine": "باروكستين",
    "venlafaxine": "فينلافاكسين",
    "quetiapine": "كويتيابين",
    "olanzapine": "أولانزابين",
    "risperidone": "ريسبيريدون",
    "lithium": "ليثيوم",
    "carbamazepine": "كاربامازيبين",
    "phenytoin": "فينيتوين",
    "valproic acid": "حمض الفالبرويك",
    "lamotrigine": "لاموتريجين",
    "diazepam": "ديازيبام",
    "alprazolam": "ألبرازولام",
    "omeprazole": "أوميبرازول",
    "pantoprazole": "بانتوبرازول",
    "esomeprazole": "إيزوميبرازول",
    "ranitidine": "رانيتيدين",
    "ondansetron": "أوندانسيترون",
    "metoclopramide": "ميتوكلوبراميد",
    "salbutamol": "سالبوتامول",
    "formoterol": "فورموتيرول",
    "montelukast": "مونتيلوكاست",
    "theophylline": "ثيوفيلين",
    "levothyroxine": "ليفوثيروكسين",
    "methimazole": "ميثيمازول",
    "methotrexate": "ميثوتريكسات",
    "dexamethasone": "ديكساميثازون",
    "prednisolone": "بريدنيزولون",
    "hydrocortisone": "هيدروكورتيزون",
    "aprepitant": "أبريبيتانت",
    "heparin": "هيبارين",
    "potassium chloride": "كلوريد البوتاسيوم",
    "promethazine": "بروميثازين",
    "tacrolimus": "تاكروليمس",
    "cyclosporine": "سيكلوسبورين",
    "sildenafil": "سيلدينافيل",
    "allopurinol": "ألوبيورينول",
    "colchicine": "كولشيسين",
    "azathioprine": "آزاثيوبرين",
}

# ===== قاموس الأسماء التجارية =====
BRAND_NAMES = {
    # مسكنات
    "advil": "ibuprofen",
    "motrin": "ibuprofen",
    "brufen": "ibuprofen",
    "nurofen": "ibuprofen",
    "voltaren": "diclofenac",
    "cataflam": "diclofenac",
    "aleve": "naproxen",
    "naprosyn": "naproxen",
    "toradol": "ketorolac",
    "celebrex": "celecoxib",
    "indocin": "indomethacin",
    "mobic": "meloxicam",
    "aspocid": "aspirin",
    "disprin": "aspirin",
    "panadol": "paracetamol",
    "tylenol": "paracetamol",
    "adol": "paracetamol",
    "ultracet": "tramadol",
    "tramal": "tramadol",
    "morphine sulfate": "morphine",
    "oxycontin": "oxycodone",
    "fentanyl citrate": "fentanyl",

    # أدوية القلب والضغط
    "coumadin": "warfarin",
    "marevan": "warfarin",
    "plavix": "clopidogrel",
    "lipitor": "atorvastatin",
    "zocor": "simvastatin",
    "crestor": "rosuvastatin",
    "zestril": "lisinopril",
    "prinivil": "lisinopril",
    "norvasc": "amlodipine",
    "concor": "bisoprolol",
    "lopressor": "metoprolol",
    "tenormin": "atenolol",
    "lasix": "furosemide",
    "aldactone": "spironolactone",
    "esidrex": "hydrochlorothiazide",
    "cozaar": "losartan",
    "diovan": "valsartan",
    "tritace": "ramipril",
    "lanoxin": "digoxin",
    "cordarone": "amiodarone",
    "nitrostat": "nitroglycerin",

    # أدوية السكر
    "glucophage": "metformin",
    "lantus": "insulin",
    "humalog": "insulin",
    "novorapid": "insulin",
    "daonil": "glibenclamide",
    "amaryl": "glimepiride",
    "januvia": "sitagliptin",

    # مضادات حيوية
    "klacid": "clarithromycin",
    "biaxin": "clarithromycin",
    "zithromax": "azithromycin",
    "zomax": "azithromycin",
    "erythrocin": "erythromycin",
    "cipro": "ciprofloxacin",
    "cifran": "ciprofloxacin",
    "levaquin": "levofloxacin",
    "avelox": "moxifloxacin",
    "rocephin": "ceftriaxone",
    "amoxil": "amoxicillin",
    "augmentin": "amoxicillin",
    "flagyl": "metronidazole",
    "vibramycin": "doxycycline",
    "rifadin": "rifampin",
    "nizoral": "ketoconazole",
    "diflucan": "fluconazole",
    "sporanox": "itraconazole",
    "zovirax": "acyclovir",

    # أدوية نفسية
    "celexa": "citalopram",
    "zoloft": "sertraline",
    "prozac": "fluoxetine",
    "paxil": "paroxetine",
    "effexor": "venlafaxine",
    "seroquel": "quetiapine",
    "zyprexa": "olanzapine",
    "risperdal": "risperidone",
    "lithobid": "lithium",
    "tegretol": "carbamazepine",
    "dilantin": "phenytoin",
    "depakine": "valproic acid",
    "lamictal": "lamotrigine",
    "valium": "diazepam",
    "xanax": "alprazolam",

    # أدوية المعدة
    "losec": "omeprazole",
    "prilosec": "omeprazole",
    "protonix": "pantoprazole",
    "nexium": "esomeprazole",
    "zantac": "ranitidine",
    "zofran": "ondansetron",
    "primperan": "metoclopramide",

    # أدوية الربو
    "ventolin": "salbutamol",
    "proventil": "salbutamol",
    "foradil": "formoterol",
    "singulair": "montelukast",
    "theo-dur": "theophylline",

    # الغدة الدرقية
    "eltroxin": "levothyroxine",
    "synthroid": "levothyroxine",
    "tapazole": "methimazole",

    # أخرى
    "methotrexate": "methotrexate",
    "rheumatrex": "methotrexate",
    "decadron": "dexamethasone",
    "solu-medrol": "prednisolone",
    "cortef": "hydrocortisone",
    "emend": "aprepitant",
    "heparin sodium": "heparin",
    "slow-k": "potassium chloride",
    "phenergan": "promethazine",
    "prograf": "tacrolimus",
    "neoral": "cyclosporine",
    "viagra": "sildenafil",
    "zyloprim": "allopurinol",
    "colcrys": "colchicine",
    "imuran": "azathioprine",
        # ===== أسماء تجارية لمصر (جديدة) =====
      "nexium": "esomeprazole",
    "neksium": "esomeprazole",
    "controloc": "pantoprazole",
    "zurcal": "pantoprazole",
    "pantoloc": "pantoprazole",
    "forxiga": "dapagliflozin",
    "xigduo": "dapagliflozin",
    "galvus": "vildagliptin",
    "covalmet": "vildagliptin",
    "atcocoxib": "etoricoxib",
    "rocoxar": "etoricoxib",
    "arcoxia": "etoricoxib",
    "neurontin": "gabapentin",
    "gabaverona": "gabapentin",
    "cialis": "tadalafil",
    "tadatrona": "tadalafil",
    "eliquis": "apixaban",
    "apixguard": "apixaban",
    "jardiance": "empagliflozin",
    "empodiab": "empagliflozin",
    "zithromax": "azithromycin",
    "azibactocin": "azithromycin",
    "crestor": "rosuvastatin",
    "coversyl": "perindopril",
    "concor": "bisoprolol",
    "dilatrend": "carvedilol",
    "cardura": "doxazosin",
    "isordil": "isosorbide dinitrate",
    "betaserc": "betahistine",
    "fosamax": "alendronate",
    "keppra": "levetiracetam",
    "cipralex": "escitalopram",
    "abilify": "aripiprazole",
    "rivotril": "clonazepam",
    "cymbalta": "duloxetine",
    "lyrica": "pregabalin",
    "januvia": "sitagliptin",
    "trajenta": "linagliptin",
    "invokana": "canagliflozin",
    "xarelto": "rivaroxaban",
    "pradaxa": "dabigatran",
    "spiriva": "tiotropium",
    "singulair": "montelukast",
}

# ===== المواد الفعالة (مع RXCUI من RxNorm) =====
INGREDIENTS = [
    # مسكنات
    {"name": "ibuprofen", "rxnorm_cui": "5640"},
    {"name": "aspirin", "rxnorm_cui": "1191"},
    {"name": "paracetamol", "rxnorm_cui": "161"},
    {"name": "naproxen", "rxnorm_cui": "7258"},
    {"name": "diclofenac", "rxnorm_cui": "3355"},
    {"name": "ketorolac", "rxnorm_cui": "35827"},
    {"name": "tramadol", "rxnorm_cui": "10689"},
    {"name": "celecoxib", "rxnorm_cui": "140587"},
    {"name": "indomethacin", "rxnorm_cui": "5781"},
    {"name": "meloxicam", "rxnorm_cui": "41493"},
    {"name": "morphine", "rxnorm_cui": "7052"},
    {"name": "codeine", "rxnorm_cui": "2670"},
    {"name": "fentanyl", "rxnorm_cui": "4337"},
    # أدوية القلب والضغط
    {"name": "warfarin", "rxnorm_cui": "11289"},
    {"name": "clopidogrel", "rxnorm_cui": "32968"},
    {"name": "atorvastatin", "rxnorm_cui": "83367"},
    {"name": "simvastatin", "rxnorm_cui": "36567"},
    {"name": "rosuvastatin", "rxnorm_cui": "301542"},
    {"name": "lisinopril", "rxnorm_cui": "29046"},
    {"name": "amlodipine", "rxnorm_cui": "17767"},
    {"name": "bisoprolol", "rxnorm_cui": "19484"},
    {"name": "metoprolol", "rxnorm_cui": "6918"},
    {"name": "atenolol", "rxnorm_cui": "1202"},
    {"name": "furosemide", "rxnorm_cui": "4603"},
    {"name": "spironolactone", "rxnorm_cui": "9997"},
    {"name": "hydrochlorothiazide", "rxnorm_cui": "5487"},
    {"name": "losartan", "rxnorm_cui": "52175"},
    {"name": "valsartan", "rxnorm_cui": "69749"},
    {"name": "ramipril", "rxnorm_cui": "35296"},
    {"name": "digoxin", "rxnorm_cui": "3407"},
    {"name": "amiodarone", "rxnorm_cui": "703"},
    {"name": "nitroglycerin", "rxnorm_cui": "7439"},
    # أدوية السكر
    {"name": "metformin", "rxnorm_cui": "6809"},
    {"name": "insulin", "rxnorm_cui": "5856"},
    {"name": "glibenclamide", "rxnorm_cui": "4815"},
    {"name": "glimepiride", "rxnorm_cui": "25789"},
    {"name": "sitagliptin", "rxnorm_cui": "593411"},
    # مضادات حيوية
    {"name": "clarithromycin", "rxnorm_cui": "21212"},
    {"name": "azithromycin", "rxnorm_cui": "18631"},
    {"name": "erythromycin", "rxnorm_cui": "4053"},
    {"name": "ciprofloxacin", "rxnorm_cui": "2551"},
    {"name": "levofloxacin", "rxnorm_cui": "82122"},
    {"name": "moxifloxacin", "rxnorm_cui": "139462"},
    {"name": "ceftriaxone", "rxnorm_cui": "2193"},
    {"name": "amoxicillin", "rxnorm_cui": "723"},
    {"name": "metronidazole", "rxnorm_cui": "6922"},
    {"name": "doxycycline", "rxnorm_cui": "3640"},
    {"name": "rifampin", "rxnorm_cui": "9384"},
    {"name": "ketoconazole", "rxnorm_cui": "6135"},
    {"name": "fluconazole", "rxnorm_cui": "4450"},
    {"name": "itraconazole", "rxnorm_cui": "28031"},
    {"name": "acyclovir", "rxnorm_cui": "281"},
    # أدوية نفسية
    {"name": "citalopram", "rxnorm_cui": "2556"},
    {"name": "sertraline", "rxnorm_cui": "36437"},
    {"name": "fluoxetine", "rxnorm_cui": "4493"},
    {"name": "paroxetine", "rxnorm_cui": "32937"},
    {"name": "venlafaxine", "rxnorm_cui": "39786"},
    {"name": "quetiapine", "rxnorm_cui": "51272"},
    {"name": "olanzapine", "rxnorm_cui": "61381"},
    {"name": "risperidone", "rxnorm_cui": "35636"},
    {"name": "lithium", "rxnorm_cui": "6448"},
    {"name": "carbamazepine", "rxnorm_cui": "2002"},
    {"name": "phenytoin", "rxnorm_cui": "8183"},
    {"name": "valproic acid", "rxnorm_cui": "11118"},
    {"name": "lamotrigine", "rxnorm_cui": "28439"},
    {"name": "diazepam", "rxnorm_cui": "3322"},
    {"name": "alprazolam", "rxnorm_cui": "596"},
    # أدوية المعدة
    {"name": "omeprazole", "rxnorm_cui": "7646"},
    {"name": "pantoprazole", "rxnorm_cui": "40790"},
    {"name": "esomeprazole", "rxnorm_cui": "283742"},
    {"name": "ranitidine", "rxnorm_cui": "9143"},
    {"name": "ondansetron", "rxnorm_cui": "26225"},
    {"name": "metoclopramide", "rxnorm_cui": "6915"},
    # أدوية الربو
    {"name": "salbutamol", "rxnorm_cui": "435"},
    {"name": "formoterol", "rxnorm_cui": "25255"},
    {"name": "montelukast", "rxnorm_cui": "88249"},
    {"name": "theophylline", "rxnorm_cui": "10460"},
    # الغدة الدرقية
    {"name": "levothyroxine", "rxnorm_cui": "10582"},
    {"name": "methimazole", "rxnorm_cui": "6835"},
    # أخرى
    {"name": "methotrexate", "rxnorm_cui": "6851"},
    {"name": "dexamethasone", "rxnorm_cui": "3264"},
    {"name": "prednisolone", "rxnorm_cui": "8638"},
    {"name": "hydrocortisone", "rxnorm_cui": "5492"},
    {"name": "aprepitant", "rxnorm_cui": "282775"},
    {"name": "heparin", "rxnorm_cui": "5224"},
    {"name": "potassium chloride", "rxnorm_cui": "8591"},
    {"name": "promethazine", "rxnorm_cui": "8745"},
    {"name": "tacrolimus", "rxnorm_cui": "42316"},
    {"name": "cyclosporine", "rxnorm_cui": "3008"},
    {"name": "sildenafil", "rxnorm_cui": "136411"},
    {"name": "allopurinol", "rxnorm_cui": "519"},
    {"name": "colchicine", "rxnorm_cui": "2683"},
        {"name": "azathioprine", "rxnorm_cui": "1256"},
    
    # ===== مواد فعالة شائعة في مصر (إضافة جديدة) =====
    {"name": "esomeprazole", "rxnorm_cui": "283742"},  # Nexium
    {"name": "pantoprazole", "rxnorm_cui": "40790"},    # Controloc
    {"name": "dapagliflozin", "rxnorm_cui": "1488564"}, # Forxiga
    {"name": "vildagliptin", "rxnorm_cui": "325840"},   # Galvus
    {"name": "etoricoxib", "rxnorm_cui": "151467"},     # Atcocoxib
    {"name": "gabapentin", "rxnorm_cui": "25480"},      # Neurontin
    {"name": "tadalafil", "rxnorm_cui": "358263"},      # Cialis
    {"name": "apixaban", "rxnorm_cui": "1364430"},      # Eliquis
    {"name": "empagliflozin", "rxnorm_cui": "1545653"}, # Jardiance
    {"name": "azithromycin", "rxnorm_cui": "18631"},    # Zithromax
    {"name": "rosuvastatin", "rxnorm_cui": "301542"},   # Crestor
    {"name": "perindopril", "rxnorm_cui": "54552"},     # Coversyl
    {"name": "bisoprolol", "rxnorm_cui": "19484"},      # Concor
    {"name": "carvedilol", "rxnorm_cui": "20352"},      # Dilatrend
    {"name": "doxazosin", "rxnorm_cui": "3523"},        # Cardura
    {"name": "isosorbide dinitrate", "rxnorm_cui": "5709"},  # Isordil
    {"name": "betahistine", "rxnorm_cui": "1515"},      # Betaserc
    {"name": "alendronate", "rxnorm_cui": "1490"},      # Fosamax
    {"name": "levetiracetam", "rxnorm_cui": "114477"},  # Keppra
    {"name": "escitalopram", "rxnorm_cui": "321988"},   # Cipralex
    {"name": "aripiprazole", "rxnorm_cui": "352272"},   # Abilify
    {"name": "clonazepam", "rxnorm_cui": "2598"},       # Rivotril
    {"name": "duloxetine", "rxnorm_cui": "72625"},      # Cymbalta
    {"name": "pregabalin", "rxnorm_cui": "187832"},     # Lyrica
    {"name": "sitagliptin", "rxnorm_cui": "593411"},    # Januvia
    {"name": "linagliptin", "rxnorm_cui": "1100699"},   # Trajenta
    {"name": "canagliflozin", "rxnorm_cui": "1372882"}, # Invokana
    {"name": "rivaroxaban", "rxnorm_cui": "1114195"},   # Xarelto
    {"name": "dabigatran", "rxnorm_cui": "1037045"},    # Pradaxa
    {"name": "tiotropium", "rxnorm_cui": "69120"},      # Spiriva
        {"name": "montelukast", "rxnorm_cui": "88249"},     # Singulair
    
    # ===== مواد فعالة من قائمة WHO (إضافة جديدة) =====
    {"name": "semaglutide", "rxnorm_cui": "1991302"},
    {"name": "dulaglutide", "rxnorm_cui": "1598394"},
    {"name": "liraglutide", "rxnorm_cui": "602888"},
    {"name": "tirzepatide", "rxnorm_cui": "2601723"},
    {"name": "rituximab", "rxnorm_cui": "121191"},
    {"name": "glatiramer", "rxnorm_cui": "1009486"},
    {"name": "cladribine", "rxnorm_cui": "2140"},
    {"name": "pembrolizumab", "rxnorm_cui": "1547545"},
    {"name": "atezolizumab", "rxnorm_cui": "1657455"},
    {"name": "zanubrutinib", "rxnorm_cui": "2288376"},
    {"name": "ibrutinib", "rxnorm_cui": "1442981"},
    {"name": "blinatumomab", "rxnorm_cui": "1599812"},
    {"name": "colistin", "rxnorm_cui": "2507"},
    {"name": "sofosbuvir", "rxnorm_cui": "1102129"},
    {"name": "velpatasvir", "rxnorm_cui": "1747692"},
    {"name": "dolutegravir", "rxnorm_cui": "1116186"},
    {"name": "tenofovir", "rxnorm_cui": "1942896"},
    {"name": "emtricitabine", "rxnorm_cui": "211338"},
    {"name": "lamivudine", "rxnorm_cui": "6825"},
    {"name": "delamanid", "rxnorm_cui": "1593673"},
    {"name": "clofazimine", "rxnorm_cui": "2579"},
    {"name": "dasatinib", "rxnorm_cui": "358312"},
    {"name": "nilotinib", "rxnorm_cui": "705793"},
    {"name": "ravidasvir", "rxnorm_cui": "2049414"},
    {"name": "ceftolozane", "rxnorm_cui": "1249352"},
    {"name": "tazobactam", "rxnorm_cui": "11314"},
]


# ===== التداخلات =====
INTERACTIONS = [
    # ========== Major (خطير) ==========
    {"a": "warfarin", "b": "aspirin", "severity": "major",
     "description": "زيادة خطر النزيف عند الجمع بين الوارفارين والأسبرين.",
     "management": "تجنب الجمع إلا لو فيه ضرورة طبية، مع متابعة INR وعلامات النزيف."},
    {"a": "warfarin", "b": "ibuprofen", "severity": "major",
     "description": "الإيبوبروفين يزيد تأثير الوارفارين وخطر النزيف.",
     "management": "يفضل استخدام الباراسيتامول كبديل. لو لازم، راقب INR."},
    {"a": "warfarin", "b": "naproxen", "severity": "major",
     "description": "النابروكسين يزيد خطر النزيف مع الوارفارين.",
     "management": "تجنب الجمع. استخدم بديل آمن للمسكن."},
    {"a": "warfarin", "b": "diclofenac", "severity": "major",
     "description": "الديكلوفيناك يزيد خطر النزيف مع الوارفارين.",
     "management": "تجنب الجمع. استخدم بديل آمن."},
    {"a": "warfarin", "b": "celecoxib", "severity": "major",
     "description": "زيادة خطر النزيف مع مضادات الالتهاب غير الستيرويدية.",
     "management": "تجنب الجمع أو راقب INR."},
    {"a": "warfarin", "b": "meloxicam", "severity": "major",
     "description": "زيادة خطر النزيف.",
     "management": "تجنب الجمع."},
    {"a": "warfarin", "b": "indomethacin", "severity": "major",
     "description": "زيادة خطر النزيف.",
     "management": "تجنب الجمع."},
    {"a": "warfarin", "b": "clarithromycin", "severity": "major",
     "description": "الكلاريثرومايسين يزيد تأثير الوارفارين بشكل كبير.",
     "management": "راقب INR عن قرب أو استخدم مضاد حيوي بديل."},
    {"a": "warfarin", "b": "azithromycin", "severity": "major",
     "description": "الأزيثرومايسين يزيد تأثير الوارفارين.",
     "management": "راقب INR."},
    {"a": "warfarin", "b": "erythromycin", "severity": "major",
     "description": "الإريثرومايسين يزيد تأثير الوارفارين.",
     "management": "راقب INR."},
    {"a": "warfarin", "b": "ciprofloxacin", "severity": "major",
     "description": "السيبروفلوكساسين يزيد تأثير الوارفارين.",
     "management": "راقب INR عن قرب."},
    {"a": "warfarin", "b": "levofloxacin", "severity": "major",
     "description": "الليفوفلوكساسين يزيد تأثير الوارفارين.",
     "management": "راقب INR."},
    {"a": "warfarin", "b": "metronidazole", "severity": "major",
     "description": "الميترونيدازول يزيد تأثير الوارفارين بشكل كبير.",
     "management": "راقب INR واستخدم جرعة أقل."},
    {"a": "warfarin", "b": "fluconazole", "severity": "major",
     "description": "الفلوكونازول يزيد تأثير الوارفارين.",
     "management": "راقب INR."},
    {"a": "warfarin", "b": "itraconazole", "severity": "major",
     "description": "الإيتراكونازول يزيد تأثير الوارفارين.",
     "management": "راقب INR."},
    {"a": "warfarin", "b": "ketoconazole", "severity": "major",
     "description": "الكيتوكونازول يزيد تأثير الوارفارين.",
     "management": "راقب INR."},
    {"a": "warfarin", "b": "phenytoin", "severity": "major",
     "description": "تفاعل معقد: الفينيتوين قد يزيد أو يقلل تأثير الوارفارين.",
     "management": "راقب INR ومستويات الفينيتوين."},
    {"a": "warfarin", "b": "carbamazepine", "severity": "major",
     "description": "الكاربامازيبين يقلل تأثير الوارفارين.",
     "management": "راقب INR وقد تحتاج زيادة جرعة الوارفارين."},
    {"a": "warfarin", "b": "rifampin", "severity": "major",
     "description": "الريفامبيسين يقلل تأثير الوارفارين بشكل كبير.",
     "management": "راقب INR. غالباً محتاج زيادة الجرعة."},
    {"a": "warfarin", "b": "amiodarone", "severity": "major",
     "description": "الأميودارون يزيد تأثير الوارفارين بشكل كبير.",
     "management": "قلل جرعة الوارفارين وراقب INR."},
    {"a": "warfarin", "b": "allopurinol", "severity": "major",
     "description": "الألوبيورينول يزيد تأثير الوارفارين.",
     "management": "راقب INR."},
    {"a": "ibuprofen", "b": "methotrexate", "severity": "major",
     "description": "الإيبوبروفين يزيد سمية الميثوتريكسات.",
     "management": "تجنب الجمع أو استخدم جرعات منخفضة تحت إشراف طبي."},
    {"a": "ibuprofen", "b": "lithium", "severity": "major",
     "description": "الإيبوبروفين يزيد مستويات الليثيوم في الدم.",
     "management": "راقب مستويات الليثيوم. يفضل بديل آمن."},
    {"a": "naproxen", "b": "lithium", "severity": "major",
     "description": "النابروكسين يزيد مستويات الليثيوم.",
     "management": "راقب مستويات الليثيوم."},
    {"a": "diclofenac", "b": "lithium", "severity": "major",
     "description": "الديكلوفيناك يزيد مستويات الليثيوم.",
     "management": "راقب مستويات الليثيوم."},
    {"a": "atorvastatin", "b": "clarithromycin", "severity": "major",
     "description": "الكلاريثرومايسين يزيد مستويات الأتورفاستاتين وخطر تلف العضلات.",
     "management": "أوقف الأتورفاستاتين مؤقتاً أثناء العلاج بالمضاد الحيوي."},
    {"a": "atorvastatin", "b": "itraconazole", "severity": "major",
     "description": "الإيتراكونازول يزيد مستويات الأتورفاستاتين.",
     "management": "قلل الجرعة أو أوقف الأتورفاستاتين."},
    {"a": "atorvastatin", "b": "ketoconazole", "severity": "major",
     "description": "الكيتوكونازول يزيد مستويات الأتورفاستاتين.",
     "management": "تجنب الجمع."},
    {"a": "simvastatin", "b": "clarithromycin", "severity": "major",
     "description": "الكلاريثرومايسين يزيد مستويات السيمفاستاتين بشكل خطير.",
     "management": "ممنوع الجمع. أوقف السيمفاستاتين."},
    {"a": "simvastatin", "b": "itraconazole", "severity": "major",
     "description": "الإيتراكونازول يزيد مستويات السيمفاستاتين بشكل خطير.",
     "management": "ممنوع الجمع."},
    {"a": "simvastatin", "b": "ketoconazole", "severity": "major",
     "description": "الكيتوكونازول يزيد مستويات السيمفاستاتين بشكل خطير.",
     "management": "ممنوع الجمع."},
    {"a": "simvastatin", "b": "erythromycin", "severity": "major",
     "description": "الإريثرومايسين يزيد مستويات السيمفاستاتين.",
     "management": "تجنب الجمع."},
    {"a": "simvastatin", "b": "amiodarone", "severity": "major",
     "description": "الأميودارون يزيد مستويات السيمفاستاتين وخطر تلف العضلات.",
     "management": "لا تتجاوز جرعة 20 مجم من السيمفاستاتين."},
    {"a": "digoxin", "b": "clarithromycin", "severity": "major",
     "description": "الكلاريثرومايسين يزيد مستويات الديجوكسين بشكل خطير.",
     "management": "راقب مستويات الديجوكسين أو استخدم مضاد حيوي بديل."},
    {"a": "digoxin", "b": "amiodarone", "severity": "major",
     "description": "الأميودارون يزيد مستويات الديجوكسين.",
     "management": "قلل جرعة الديجوكسين وراقب المستويات."},
    {"a": "citalopram", "b": "tramadol", "severity": "major",
     "description": "خطر متلازمة السيروتونين والنوبات.",
     "management": "تجنب الجمع. استخدم مسكن بديل."},
    {"a": "sertraline", "b": "tramadol", "severity": "major",
     "description": "خطر متلازمة السيروتونين.",
     "management": "تجنب الجمع."},
    {"a": "fluoxetine", "b": "tramadol", "severity": "major",
     "description": "خطر متلازمة السيروتونين والنوبات.",
     "management": "تجنب الجمع."},
    {"a": "paroxetine", "b": "tramadol", "severity": "major",
     "description": "خطر متلازمة السيروتونين.",
     "management": "تجنب الجمع."},
    {"a": "venlafaxine", "b": "tramadol", "severity": "major",
     "description": "خطر متلازمة السيروتونين.",
     "management": "تجنب الجمع."},
    {"a": "clopidogrel", "b": "omeprazole", "severity": "major",
     "description": "الأوميبرازول يقلل تأثير الكلوبيدوجريل المضاد للصفائح.",
     "management": "استخدم بانتوبرازول بدلاً منه."},
    {"a": "clopidogrel", "b": "esomeprazole", "severity": "major",
     "description": "الإيزوميبرازول يقلل تأثير الكلوبيدوجريل.",
     "management": "استخدم بانتوبرازول بدلاً منه."},
    {"a": "theophylline", "b": "ciprofloxacin", "severity": "major",
     "description": "السيبروفلوكساسين يزيد مستويات الثيوفيلين وسميته.",
     "management": "راقب مستويات الثيوفيلين أو استخدم مضاد حيوي بديل."},
    {"a": "theophylline", "b": "erythromycin", "severity": "major",
     "description": "الإريثرومايسين يزيد مستويات الثيوفيلين.",
     "management": "راقب مستويات الثيوفيلين."},
    {"a": "theophylline", "b": "clarithromycin", "severity": "major",
     "description": "الكلاريثرومايسين يزيد مستويات الثيوفيلين.",
     "management": "راقب مستويات الثيوفيلين."},
    {"a": "methotrexate", "b": "aspirin", "severity": "major",
     "description": "الأسبرين يقلل إفراز الميثوتريكسات ويزيد سميته.",
     "management": "تجنب الجمع أو راقب مستويات الميثوتريكسات."},
    {"a": "methotrexate", "b": "ibuprofen", "severity": "major",
     "description": "الإيبوبروفين يزيد سمية الميثوتريكسات.",
     "management": "تجنب الجمع."},
    {"a": "methotrexate", "b": "naproxen", "severity": "major",
     "description": "النابروكسين يزيد سمية الميثوتريكسات.",
     "management": "تجنب الجمع."},
    {"a": "tacrolimus", "b": "clarithromycin", "severity": "major",
     "description": "الكلاريثرومايسين يزيد مستويات التاكروليمس بشكل خطير.",
     "management": "راقب مستويات التاكروليمس أو استخدم مضاد حيوي بديل."},
    {"a": "tacrolimus", "b": "ketoconazole", "severity": "major",
     "description": "الكيتوكونازول يزيد مستويات التاكروليمس.",
     "management": "تجنب الجمع أو راقب المستويات عن قرب."},
    {"a": "tacrolimus", "b": "itraconazole", "severity": "major",
     "description": "الإيتراكونازول يزيد مستويات التاكروليمس.",
     "management": "راقب المستويات."},
    {"a": "cyclosporine", "b": "clarithromycin", "severity": "major",
     "description": "الكلاريثرومايسين يزيد مستويات السيكلوسبورين.",
     "management": "راقب مستويات السيكلوسبورين."},
    {"a": "cyclosporine", "b": "ketoconazole", "severity": "major",
     "description": "الكيتوكونازول يزيد مستويات السيكلوسبورين.",
     "management": "راقب المستويات."},
    {"a": "cyclosporine", "b": "itraconazole", "severity": "major",
     "description": "الإيتراكونازول يزيد مستويات السيكلوسبورين.",
     "management": "راقب المستويات."},
    {"a": "azathioprine", "b": "allopurinol", "severity": "major",
     "description": "الألوبيورينول يزيد سمية الآزاثيوبرين بشكل خطير.",
     "management": "قلل جرعة الآزاثيوبرين أو استخدم بديل."},
    {"a": "lithium", "b": "hydrochlorothiazide", "severity": "major",
     "description": "مدرات البول الثيازيدية تزيد مستويات الليثيوم بشكل خطير.",
     "management": "راقب مستويات الليثيوم عن قرب."},
    {"a": "lithium", "b": "furosemide", "severity": "major",
     "description": "الفوروسيميد يزيد مستويات الليثيوم.",
     "management": "راقب مستويات الليثيوم."},
    {"a": "lithium", "b": "lisinopril", "severity": "major",
     "description": "مثبطات ACE تزيد مستويات الليثيوم.",
     "management": "راقب مستويات الليثيوم."},
    {"a": "lithium", "b": "losartan", "severity": "major",
     "description": "اللوسارتان يزيد مستويات الليثيوم.",
     "management": "راقب مستويات الليثيوم."},
    {"a": "amiodarone", "b": "levothyroxine", "severity": "major",
     "description": "الأميودارون يؤثر على وظائف الغدة الدرقية.",
     "management": "راقب وظائف الغدة الدرقية."},
    {"a": "methimazole", "b": "warfarin", "severity": "major",
     "description": "الميثيمازول يقلل تأثير الوارفارين.",
     "management": "راقب INR."},
    {"a": "colchicine", "b": "clarithromycin", "severity": "major",
     "description": "الكلاريثرومايسين يزيد سمية الكولشيسين.",
     "management": "تجنب الجمع أو قلل الجرعة."},
    {"a": "colchicine", "b": "ketoconazole", "severity": "major",
     "description": "الكيتوكونازول يزيد سمية الكولشيسين.",
     "management": "تجنب الجمع."},
    {"a": "colchicine", "b": "cyclosporine", "severity": "major",
     "description": "السيكلوسبورين يزيد سمية الكولشيسين.",
     "management": "تجنب الجمع أو قلل الجرعة."},
    {"a": "sildenafil", "b": "nitroglycerin", "severity": "major",
     "description": "انخفاض خطير في ضغط الدم.",
     "management": "ممنوع الجمع تماماً."},
    # ========== Moderate (متوسط) ==========
    {"a": "aspirin", "b": "ibuprofen", "severity": "moderate",
     "description": "الإيبوبروفين يقلل تأثير الأسبرين المضاد للصفائح، ويزيد خطر النزيف المعوي.",
     "management": "خد الأسبرين قبل الإيبوبروفين بساعتين على الأقل، أو استخدم مسكن بديل."},
    {"a": "aspirin", "b": "clopidogrel", "severity": "moderate",
     "description": "زيادة خطر النزيف عند الجمع بين مضادين للصفائح.",
     "management": "المراقبة الدقيقة لعلامات النزيف."},
    {"a": "aspirin", "b": "heparin", "severity": "moderate",
     "description": "زيادة خطر النزيف عند الجمع بين مضادين للتخثر.",
     "management": "راقب علامات النزيف."},
    {"a": "clopidogrel", "b": "heparin", "severity": "moderate",
     "description": "زيادة خطر النزيف عند الجمع.",
     "management": "راقب علامات النزيف."},
    {"a": "ibuprofen", "b": "naproxen", "severity": "moderate",
     "description": "الجمع بين مضادين غير ستيرويديين يزيد خطر النزيف المعوي والفشل الكلوي.",
     "management": "تجنب الجمع."},
    {"a": "ibuprofen", "b": "diclofenac", "severity": "moderate",
     "description": "الجمع بين مضادين غير ستيرويديين يزيد الآثار الجانبية.",
     "management": "تجنب الجمع."},
    {"a": "ibuprofen", "b": "celecoxib", "severity": "moderate",
     "description": "زيادة خطر الآثار الجانبية المعوية والكلوية.",
     "management": "تجنب الجمع."},
    {"a": "ibuprofen", "b": "lisinopril", "severity": "moderate",
     "description": "الإيبوبروفين يقلل تأثير الليسينوبريل على ضغط الدم وقد يضر الكلى.",
     "management": "راقب ضغط الدم ووظائف الكلى."},
    {"a": "ibuprofen", "b": "losartan", "severity": "moderate",
     "description": "الإيبوبروفين يقلل تأثير اللوسارتان وقد يضر الكلى.",
     "management": "راقب ضغط الدم ووظائف الكلى."},
    {"a": "ibuprofen", "b": "furosemide", "severity": "moderate",
     "description": "الإيبوبروفين يقلل تأثير مدرات البول.",
     "management": "راقب استجابة المريض للمدرات."},
    {"a": "ibuprofen", "b": "spironolactone", "severity": "moderate",
     "description": "خطر ارتفاع البوتاسيوم.",
     "management": "راقب البوتاسيوم ووظائف الكلى."},
    {"a": "naproxen", "b": "lisinopril", "severity": "moderate",
     "description": "النابروكسين يقلل تأثير الليسينوبريل.",
     "management": "راقب ضغط الدم."},
    {"a": "diclofenac", "b": "lisinopril", "severity": "moderate",
     "description": "الديكلوفيناك يقلل تأثير الليسينوبريل.",
     "management": "راقب ضغط الدم."},
    {"a": "celecoxib", "b": "lisinopril", "severity": "moderate",
     "description": "يقلل تأثير الليسينوبريل.",
     "management": "راقب ضغط الدم."},
    {"a": "simvastatin", "b": "amlodipine", "severity": "moderate",
     "description": "الأملوديبين يزيد مستويات السيمفاستاتين.",
     "management": "لا تتجاوز جرعة 20 مجم."},
    {"a": "digoxin", "b": "furosemide", "severity": "moderate",
     "description": "الفوروسيميد يقلل البوتاسيوم مما يزيد سمية الديجوكسين.",
     "management": "راقب البوتاسيوم ومستويات الديجوكسين."},
    {"a": "digoxin", "b": "spironolactone", "severity": "moderate",
     "description": "السبيرونولاكتون يزيد مستويات الديجوكسين.",
     "management": "راقب مستويات الديجوكسين."},
    {"a": "digoxin", "b": "hydrochlorothiazide", "severity": "moderate",
     "description": "الثيازيدات تقلل البوتاسيوم مما يزيد سمية الديجوكسين.",
     "management": "راقب البوتاسيوم."},
    {"a": "citalopram", "b": "aspirin", "severity": "moderate",
     "description": "زيادة خطر النزيف المعوي.",
     "management": "راقب علامات النزيف."},
    {"a": "sertraline", "b": "aspirin", "severity": "moderate",
     "description": "زيادة خطر النزيف المعوي.",
     "management": "راقب علامات النزيف."},
    {"a": "fluoxetine", "b": "aspirin", "severity": "moderate",
     "description": "زيادة خطر النزيف المعوي.",
     "management": "راقب علامات النزيف."},
    {"a": "paroxetine", "b": "aspirin", "severity": "moderate",
     "description": "زيادة خطر النزيف المعوي.",
     "management": "راقب علامات النزيف."},
    {"a": "venlafaxine", "b": "aspirin", "severity": "moderate",
     "description": "زيادة خطر النزيف المعوي.",
     "management": "راقب علامات النزيف."},
    {"a": "citalopram", "b": "ibuprofen", "severity": "moderate",
     "description": "زيادة خطر النزيف المعوي.",
     "management": "راقب علامات النزيف."},
    {"a": "sertraline", "b": "ibuprofen", "severity": "moderate",
     "description": "زيادة خطر النزيف المعوي.",
     "management": "راقب علامات النزيف."},
    {"a": "fluoxetine", "b": "ibuprofen", "severity": "moderate",
     "description": "زيادة خطر النزيف المعوي.",
     "management": "راقب علامات النزيف."},
    {"a": "paroxetine", "b": "ibuprofen", "severity": "moderate",
     "description": "زيادة خطر النزيف المعوي.",
     "management": "راقب علامات النزيف."},
    {"a": "citalopram", "b": "naproxen", "severity": "moderate",
     "description": "زيادة خطر النزيف المعوي.",
     "management": "راقب علامات النزيف."},
    {"a": "sertraline", "b": "naproxen", "severity": "moderate",
     "description": "زيادة خطر النزيف المعوي.",
     "management": "راقب علامات النزيف."},
    {"a": "omeprazole", "b": "clopidogrel", "severity": "moderate",
     "description": "الأوميبرازول يقلل تأثير الكلوبيدوجريل المضاد للصفائح.",
     "management": "استخدم بانتوبرازول بدلاً منه."},
    {"a": "paracetamol", "b": "warfarin", "severity": "moderate",
     "description": "الباراسيتامول بجرعات عالية لعدة أيام يزيد تأثير الوارفارين.",
     "management": "راقب INR لو الاستخدام أكثر من أسبوع."},
    {"a": "amlodipine", "b": "furosemide", "severity": "moderate",
     "description": "الجمع قد يسبب انخفاض ضغط الدم.",
     "management": "راقب ضغط الدم."},
    {"a": "ceftriaxone", "b": "furosemide", "severity": "moderate",
     "description": "زيادة خطر سمية الكلى.",
     "management": "راقب وظائف الكلى."},
    {"a": "furosemide", "b": "formoterol", "severity": "moderate",
     "description": "انخفاض البوتاسيوم في الدم.",
     "management": "راقب البوتاسيوم."},
    {"a": "formoterol", "b": "hydrocortisone", "severity": "moderate",
     "description": "انخفاض البوتاسيوم في الدم.",
     "management": "راقب البوتاسيوم."},
    {"a": "furosemide", "b": "hydrocortisone", "severity": "moderate",
     "description": "انخفاض البوتاسيوم في الدم.",
     "management": "راقب البوتاسيوم."},
    {"a": "furosemide", "b": "prednisolone", "severity": "moderate",
     "description": "انخفاض البوتاسيوم في الدم.",
     "management": "راقب البوتاسيوم."},
    {"a": "furosemide", "b": "dexamethasone", "severity": "moderate",
     "description": "انخفاض البوتاسيوم في الدم.",
     "management": "راقب البوتاسيوم."},
    {"a": "furosemide", "b": "salbutamol", "severity": "moderate",
     "description": "انخفاض البوتاسيوم في الدم.",
     "management": "راقب البوتاسيوم."},
    {"a": "losartan", "b": "furosemide", "severity": "moderate",
     "description": "زيادة تأثير انخفاض ضغط الدم أو سمية الكلى.",
     "management": "راقب ضغط الدم ووظائف الكلى."},
    {"a": "losartan", "b": "spironolactone", "severity": "moderate",
     "description": "خطر ارتفاع البوتاسيوم.",
     "management": "راقب البوتاسيوم."},
    {"a": "lisinopril", "b": "spironolactone", "severity": "moderate",
     "description": "خطر ارتفاع البوتاسيوم.",
     "management": "راقب البوتاسيوم."},
    {"a": "lisinopril", "b": "potassium chloride", "severity": "moderate",
     "description": "خطر ارتفاع البوتاسيوم.",
     "management": "راقب البوتاسيوم."},
    {"a": "levofloxacin", "b": "aspirin", "severity": "moderate",
     "description": "الأسبرين قد يقلل تركيز الكينولونات.",
     "management": "راقب فعالية المضاد الحيوي."},
    {"a": "furosemide", "b": "aspirin", "severity": "moderate",
     "description": "زيادة تركيز الساليسيلات.",
     "management": "راقب علامات سمية الساليسيلات."},
    {"a": "aprepitant", "b": "dexamethasone", "severity": "moderate",
     "description": "الأبريبيتانت يزيد تركيز الديكساميثازون.",
     "management": "قلل جرعة الديكساميثازون."},
    {"a": "aprepitant", "b": "prednisolone", "severity": "moderate",
     "description": "الأبريبيتانت يزيد تركيز الكورتيكوستيرويدات.",
     "management": "قلل الجرعة."},
    {"a": "valproic acid", "b": "aspirin", "severity": "moderate",
     "description": "الأسبرين يزيد مستويات حمض الفالبرويك.",
     "management": "راقب مستويات حمض الفالبرويك."},
    {"a": "quetiapine", "b": "ketorolac", "severity": "moderate",
     "description": "زيادة خطر الآثار الجانبية.",
     "management": "راقب المريض."},
    {"a": "quetiapine", "b": "hydrochlorothiazide", "severity": "moderate",
     "description": "زيادة خطر انخفاض ضغط الدم.",
     "management": "راقب ضغط الدم."},
    {"a": "olanzapine", "b": "diazepam", "severity": "moderate",
     "description": "زيادة التهدئة وانخفاض ضغط الدم.",
     "management": "راقب المريض."},
    {"a": "risperidone", "b": "furosemide", "severity": "moderate",
     "description": "زيادة خطر انخفاض ضغط الدم.",
     "management": "راقب ضغط الدم."},
    {"a": "diazepam", "b": "morphine", "severity": "moderate",
     "description": "زيادة التهدئة واكتئاب الجهاز التنفسي.",
     "management": "راقب التنفس."},
    {"a": "alprazolam", "b": "morphine", "severity": "moderate",
     "description": "زيادة التهدئة واكتئاب الجهاز التنفسي.",
     "management": "راقب التنفس."},
    {"a": "tramadol", "b": "diazepam", "severity": "moderate",
     "description": "زيادة التهدئة واكتئاب الجهاز التنفسي.",
     "management": "راقب التنفس."},
    {"a": "codeine", "b": "diazepam", "severity": "moderate",
     "description": "زيادة التهدئة.",
     "management": "راقب المريض."},
    {"a": "metformin", "b": "furosemide", "severity": "minor",
     "description": "مدرات البول قد تزيد أو تقلل تأثير الميتفورمين.",
     "management": "راقب مستويات السكر."},
    {"a": "clopidogrel", "b": "atorvastatin", "severity": "minor",
     "description": "الأتورفاستاتين قد يقلل تأثير الكلوبيدوجريل.",
     "management": "راقب فعالية الكلوبيدوجريل."},
    {"a": "metformin", "b": "pantoprazole", "severity": "minor",
     "description": "البانتوبرازول قد يزيد تركيز الميتفورمين.",
     "management": "راقب مستويات السكر."},
        {"a": "levothyroxine", "b": "omeprazole", "severity": "moderate",
     "description": "الأوميبرازول يقلل امتصاص الليفوثيروكسين.",
     "management": "خد الليفوثيروكسين على معدة فاضية قبل الأوميبرازول بـ 4 ساعات."},
    {"a": "levothyroxine", "b": "pantoprazole", "severity": "moderate",
     "description": "البانتوبرازول يقلل امتصاص الليفوثيروكسين.",
     "management": "خد الليفوثيروكسين على معدة فاضية."},
    
    # ========== مضادات التجلط الجديدة ==========
    {"a": "apixaban", "b": "aspirin", "severity": "major",
     "description": "زيادة خطر النزيف عند الجمع بين مضادي التجلط.",
     "management": "تجنب الجمع إلا تحت إشراف طبي. راقب علامات النزيف."},
    {"a": "apixaban", "b": "ibuprofen", "severity": "major",
     "description": "الإيبوبروفين يزيد خطر النزيف مع الأبيكسابان.",
     "management": "تجنب الجمع. استخدم باراسيتامول كبديل."},
    {"a": "apixaban", "b": "naproxen", "severity": "major",
     "description": "زيادة خطر النزيف.",
     "management": "تجنب الجمع."},
    {"a": "apixaban", "b": "diclofenac", "severity": "major",
     "description": "زيادة خطر النزيف.",
     "management": "تجنب الجمع."},
    {"a": "apixaban", "b": "warfarin", "severity": "major",
     "description": "ممنوع الجمع - خطر نزيف شديد.",
     "management": "ممنوع الجمع تماماً. استشر الطبيب."},
    {"a": "apixaban", "b": "clopidogrel", "severity": "major",
     "description": "زيادة خطر النزيف.",
     "management": "تجنب الجمع إلا تحت إشراف طبي."},
    {"a": "apixaban", "b": "heparin", "severity": "major",
     "description": "زيادة خطر النزيف.",
     "management": "راقب علامات النزيف."},
    {"a": "rivaroxaban", "b": "aspirin", "severity": "major",
     "description": "زيادة خطر النزيف.",
     "management": "تجنب الجمع إلا تحت إشراف طبي."},
    {"a": "rivaroxaban", "b": "ibuprofen", "severity": "major",
     "description": "زيادة خطر النزيف.",
     "management": "تجنب الجمع. استخدم باراسيتامول كبديل."},
    {"a": "rivaroxaban", "b": "warfarin", "severity": "major",
     "description": "ممنوع الجمع - خطر نزيف شديد.",
     "management": "ممنوع الجمع."},
    {"a": "rivaroxaban", "b": "clopidogrel", "severity": "major",
     "description": "زيادة خطر النزيف.",
     "management": "راقب علامات النزيف."},
    {"a": "dabigatran", "b": "aspirin", "severity": "major",
     "description": "زيادة خطر النزيف.",
     "management": "تجنب الجمع إلا تحت إشراف طبي."},
    {"a": "dabigatran", "b": "ibuprofen", "severity": "major",
     "description": "زيادة خطر النزيف.",
     "management": "تجنب الجمع."},
    {"a": "dabigatran", "b": "warfarin", "severity": "major",
     "description": "ممنوع الجمع.",
     "management": "ممنوع الجمع."},
    {"a": "dabigatran", "b": "clopidogrel", "severity": "major",
     "description": "زيادة خطر النزيف.",
     "management": "راقب علامات النزيف."},
    
    # ========== مضادات الاكتئاب الجديدة ==========
    {"a": "escitalopram", "b": "tramadol", "severity": "major",
     "description": "خطر متلازمة السيروتونين.",
     "management": "تجنب الجمع. استخدم مسكن بديل."},
    {"a": "escitalopram", "b": "aspirin", "severity": "moderate",
     "description": "زيادة خطر النزيف المعوي.",
     "management": "راقب علامات النزيف."},
    {"a": "escitalopram", "b": "ibuprofen", "severity": "moderate",
     "description": "زيادة خطر النزيف المعوي.",
     "management": "راقب علامات النزيف."},
    {"a": "escitalopram", "b": "naproxen", "severity": "moderate",
     "description": "زيادة خطر النزيف المعوي.",
     "management": "راقب علامات النزيف."},
    {"a": "escitalopram", "b": "warfarin", "severity": "major",
     "description": "زيادة خطر النزيف.",
     "management": "راقب INR وعلامات النزيف."},
    {"a": "duloxetine", "b": "tramadol", "severity": "major",
     "description": "خطر متلازمة السيروتونين.",
     "management": "تجنب الجمع."},
    {"a": "duloxetine", "b": "aspirin", "severity": "moderate",
     "description": "زيادة خطر النزيف المعوي.",
     "management": "راقب علامات النزيف."},
    {"a": "duloxetine", "b": "ibuprofen", "severity": "moderate",
     "description": "زيادة خطر النزيف المعوي.",
     "management": "راقب علامات النزيف."},
    {"a": "duloxetine", "b": "warfarin", "severity": "major",
     "description": "زيادة خطر النزيف.",
     "management": "راقب INR."},
    
    # ========== مضادات الصرع والأعصاب ==========
    {"a": "gabapentin", "b": "morphine", "severity": "moderate",
     "description": "زيادة التهدئة واكتئاب التنفس.",
     "management": "راقب التنفس."},
    {"a": "gabapentin", "b": "tramadol", "severity": "moderate",
     "description": "زيادة التهدئة.",
     "management": "راقب المريض."},
    {"a": "gabapentin", "b": "diazepam", "severity": "moderate",
     "description": "زيادة التهدئة.",
     "management": "راقب المريض."},
    {"a": "pregabalin", "b": "morphine", "severity": "moderate",
     "description": "زيادة التهدئة واكتئاب التنفس.",
     "management": "راقب التنفس."},
    {"a": "pregabalin", "b": "tramadol", "severity": "moderate",
     "description": "زيادة التهدئة.",
     "management": "راقب المريض."},
    {"a": "pregabalin", "b": "diazepam", "severity": "moderate",
     "description": "زيادة التهدئة.",
     "management": "راقب المريض."},
    {"a": "levetiracetam", "b": "carbamazepine", "severity": "moderate",
     "description": "تفاعل معقد - مراقبة المستويات.",
     "management": "راقب مستويات الدواء."},
    
    # ========== البنزوديازيبينات ==========
    {"a": "clonazepam", "b": "morphine", "severity": "moderate",
     "description": "اكتئاب التنفس.",
     "management": "راقب التنفس."},
    {"a": "clonazepam", "b": "tramadol", "severity": "moderate",
     "description": "زيادة التهدئة.",
     "management": "راقب المريض."},
    {"a": "clonazepam", "b": "diazepam", "severity": "moderate",
     "description": "زيادة التهدئة.",
     "management": "راقب المريض."},
    
    # ========== مضادات الالتهاب الجديدة ==========
    {"a": "etoricoxib", "b": "warfarin", "severity": "major",
     "description": "زيادة خطر النزيف.",
     "management": "تجنب الجمع. راقب INR."},
    {"a": "etoricoxib", "b": "aspirin", "severity": "moderate",
     "description": "زيادة خطر النزيف المعوي.",
     "management": "تجنب الجمع."},
    {"a": "etoricoxib", "b": "ibuprofen", "severity": "moderate",
     "description": "تجنب الجمع بين مضادين غير ستيرويديين.",
     "management": "تجنب الجمع."},
    {"a": "etoricoxib", "b": "naproxen", "severity": "moderate",
     "description": "تجنب الجمع.",
     "management": "تجنب الجمع."},
    {"a": "etoricoxib", "b": "lisinopril", "severity": "moderate",
     "description": "يقلل تأثير الليسينوبريل.",
     "management": "راقب ضغط الدم."},
    {"a": "etoricoxib", "b": "furosemide", "severity": "moderate",
     "description": "يقلل تأثير مدرات البول.",
     "management": "راقب استجابة المريض."},
    {"a": "etoricoxib", "b": "losartan", "severity": "moderate",
     "description": "يقلل تأثير اللوسارتان.",
     "management": "راقب ضغط الدم."},
    
    # ========== مضادات حيوية ==========
    {"a": "azithromycin", "b": "warfarin", "severity": "major",
     "description": "يزيد تأثير الوارفارين.",
     "management": "راقب INR."},
    {"a": "azithromycin", "b": "digoxin", "severity": "moderate",
     "description": "يزيد مستويات الديجوكسين.",
     "management": "راقب مستويات الديجوكسين."},
    {"a": "azithromycin", "b": "amiodarone", "severity": "major",
     "description": "خطر اضطراب نظم القلب.",
     "management": "تجنب الجمع."},
    
    # ========== أدوية السكري الجديدة ==========
    {"a": "dapagliflozin", "b": "furosemide", "severity": "moderate",
     "description": "خطر الجفاف.",
     "management": "راقب السوائل."},
    {"a": "dapagliflozin", "b": "insulin", "severity": "moderate",
     "description": "خطر نقص السكر.",
     "management": "راقب مستويات السكر."},
    {"a": "empagliflozin", "b": "furosemide", "severity": "moderate",
     "description": "خطر الجفاف.",
     "management": "راقب السوائل."},
    {"a": "empagliflozin", "b": "insulin", "severity": "moderate",
     "description": "خطر نقص السكر.",
     "management": "راقب مستويات السكر."},
    {"a": "vildagliptin", "b": "insulin", "severity": "moderate",
     "description": "خطر نقص السكر.",
     "management": "راقب مستويات السكر."},
    {"a": "vildagliptin", "b": "glibenclamide", "severity": "moderate",
     "description": "خطر نقص السكر.",
     "management": "راقب مستويات السكر."},
    
    # ========== مضادات الذهان ==========
    {"a": "aripiprazole", "b": "diazepam", "severity": "moderate",
     "description": "زيادة التهدئة.",
     "management": "راقب المريض."},
    {"a": "aripiprazole", "b": "carbamazepine", "severity": "moderate",
     "description": "يقلل مستويات الأريبيبرازول.",
     "management": "راقب فعالية الدواء."},
    
    # ========== السيلدينافيل والتادالافيل ==========
    {"a": "tadalafil", "b": "nitroglycerin", "severity": "major",
     "description": "انخفاض خطير في ضغط الدم - ممنوع الجمع.",
     "management": "ممنوع الجمع تماماً."},
    {"a": "tadalafil", "b": "amlodipine", "severity": "moderate",
     "description": "انخفاض ضغط الدم.",
     "management": "راقب ضغط الدم."},
    
    # ========== أدوية الحموضة ==========
    {"a": "esomeprazole", "b": "clopidogrel", "severity": "major",
     "description": "يقلل تأثير الكلوبيدوجريل.",
     "management": "استخدم بانتوبرازول بدلاً منه."},
]


def load_data():
    """تعبئة قاعدة البيانات بالبيانات المبدئية"""
    session = Session()

    try:
        # ===== إضافة المواد الفعالة =====
        print("📥 جاري إضافة المواد الفعالة...")
        ingredient_map = {}
        added_ingredients = 0

        for item in INGREDIENTS:
            existing = session.query(ActiveIngredient).filter_by(name=item["name"]).first()
            name_ar = ARABIC_NAMES.get(item["name"])

            if not existing:
                ing = ActiveIngredient(
                    name=item["name"],
                    name_ar=name_ar,
                    rxnorm_cui=item["rxnorm_cui"]
                )
                session.add(ing)
                session.flush()
                ingredient_map[item["name"]] = ing.id
                added_ingredients += 1
            else:
                if name_ar and not existing.name_ar:
                    existing.name_ar = name_ar
                ingredient_map[item["name"]] = existing.id

        session.commit()
        print(f"✅ تمت إضافة {added_ingredients} مادة فعالة جديدة (الإجمالي: {len(ingredient_map)})")

        # ===== إضافة الأسماء التجارية =====
        print("\n📥 جاري إضافة الأسماء التجارية...")
        added_brands = 0
        for brand, ing_name in BRAND_NAMES.items():
            ing_id = ingredient_map.get(ing_name)
            if not ing_id:
                continue
            existing = session.query(BrandName).filter_by(brand_name=brand).first()
            if not existing:
                session.add(BrandName(brand_name=brand, ingredient_id=ing_id))
                added_brands += 1
        session.commit()
        print(f"✅ تمت إضافة {added_brands} اسم تجاري جديد")

        # ===== إضافة التداخلات =====
        print("\n📥 جاري إضافة التداخلات...")
        added = 0
        skipped = 0

        for inter in INTERACTIONS:
            a_id = ingredient_map.get(inter["a"])
            b_id = ingredient_map.get(inter["b"])

            if not a_id or not b_id:
                print(f"⚠️ مادة غير موجودة: {inter['a']} أو {inter['b']}")
                continue

            if a_id > b_id:
                a_id, b_id = b_id, a_id

            existing = session.query(Interaction).filter_by(
                ingredient_a_id=a_id,
                ingredient_b_id=b_id
            ).first()

            if not existing:
                interaction = Interaction(
                    ingredient_a_id=a_id,
                    ingredient_b_id=b_id,
                    severity=inter["severity"],
                    description=inter["description"],
                    management=inter["management"],
                    source="manual"
                )
                session.add(interaction)
                added += 1
            else:
                skipped += 1

        session.commit()
        print(f"✅ تمت إضافة {added} تداخل دوائي جديد (تم تخطي {skipped} موجود)")

    except Exception as e:
        session.rollback()
        print(f"❌ خطأ: {e}")
    finally:
        session.close()


if __name__ == "__main__":
    load_data()